ProViewer SDK: bvt_c/bvt_sdk.h File Reference
bvt_c/bvt_sdk.h File Reference
Functions
int BVTSDK_MajorVersion ()
int BVTSDK_MinorVersion ()
int BVTSDK_BuildNumber ()
Function Documentation
int BVTSDK_MajorVersion ()
Return the major version number of the SDK.
Referenced by BVTSDK::SDK::MajorVersion().
int BVTSDK_MinorVersion ()
Return the minor version of the SDK.
Referenced by BVTSDK::SDK::MinorVersion().
int BVTSDK_BuildNumber ()
Return the build number of the SDK.
Referenced by BVTSDK::SDK::BuildNumber().