ProViewer SDK: BVTSDK::NavData Class Reference
BVTSDK::NavData Class Reference
NavData contains various types of user-accessible navigation parameter, which can be saved to and retrieved from a sonar file on a per ping basis.
Public Member Functions
NavData ()
~NavData ()
RetVal Clone (const NavData &navdata_to_clone)
RetVal GetLatitude (double *degrees)
RetVal SetLatitude (double degrees)
RetVal GetLongitude (double *degrees)
RetVal SetLongitude (double degrees)
RetVal GetHorizontalPrecisionError (float *error_meters)
RetVal SetHorizontalPrecisionError (float error_meters)
RetVal GetHeight (float *meters_above_geoid)
RetVal SetHeight (float meters_above_geoid)
RetVal GetVerticalPrecisionError (float *error_meters)
RetVal SetVerticalPrecisionError (float error_meters)
RetVal GetDepth (float *meters_below_surface)
RetVal SetDepth (float meters_below_surface)
RetVal GetAltitude (float *meters_above_bottom)
RetVal SetAltitude (float meters_above_bottom)
RetVal GetHeading (float *degrees_true)
RetVal SetHeading (float degrees_true)
RetVal GetHeadingVelocity (float *meters_per_second)
RetVal SetHeadingVelocity (float meters_per_second)
RetVal GetCourseOverGround (float *degrees_true)
RetVal SetCourseOverGround (float degrees_true)
RetVal GetSpeedOverGround (float *meters_per_second)
RetVal SetSpeedOverGround (float meters_per_second)
RetVal GetPitchAngle (float *degrees_bow_up)
RetVal SetPitchAngle (float degrees_bow_up)
RetVal GetRollAngle (float *degrees_port_up)
RetVal SetRollAngle (float degrees_port_up)
RetVal GetYawAngle (float *degrees_bow_to_starboard)
RetVal SetYawAngle (float degrees_bow_to_starboard)
RetVal GetPitchRate (float *degrees_per_second)
RetVal SetPitchRate (float degrees_per_second)
RetVal GetRollRate (float *degrees_per_second)
RetVal SetRollRate (float degrees_per_second)
RetVal GetYawRate (float *degrees_per_second)
RetVal SetYawRate (float degrees_per_second)
RetVal GetAccelerationX (float *accel_mg)
RetVal SetAccelerationX (float accel_mg)
RetVal GetAccelerationY (float *accel_mg)
RetVal SetAccelerationY (float accel_mg)
RetVal GetAccelerationZ (float *accel_mg)
RetVal SetAccelerationZ (float accel_mg)
RetVal GetOffsetNorth (double *meters)
RetVal SetOffsetNorth (double meters)
RetVal GetOffsetEast (double *meters)
RetVal SetOffsetEast (double meters)
RetVal GetOffsetIsFromLatLongFlag (int *is_true)
RetVal SetOffsetIsFromLatLongFlag (int is_true)
std::string GetUserNavString ()
RetVal SetUserNavString (std::string string_in)
double GetTimestamp ()
RetVal SetTimestamp (double sec)
Detailed Description
NavData contains various types of user-accessible navigation parameter, which can be saved to and retrieved from a sonar file on a per ping basis.
The NavData objects can be created and destroyed as needed. When the ping functions are called to get or put the data, the data is copied. This allows NavData objects to be pre-allocated and filled from various instrument sources. It also allows the data to be copied from one NavData object to the other. NOTE: NavData changes will only be saved to a sonar of type FILE.
Constructor & Destructor Documentation
BVTSDK::NavData::NavData () [inline]
Create the object.
References BVTNavData_Create().
BVTSDK::NavData::~NavData () [inline]
Destroy the object.
References BVTNavData_Destroy().
Member Function Documentation
RetVal BVTSDK::NavData::Clone (const NavData & navdata_to_clone) [inline]
Clones the data from the passed NavData object to this object.
Both objects must have already been created.
Parameters:
navdata_to_clone existing NavData object to copy from
References BVTNavData_Clone().
RetVal BVTSDK::NavData::GetLatitude (double * degrees) [inline]
Returns the latitude.
If no latitude was stored, returns BVT_NAV_NO_DATA.
Parameters:
degrees latitude in degrees
References BVTNavData_GetLatitude().
RetVal BVTSDK::NavData::SetLatitude (double degrees) [inline]
Stores the latitude, as a signed floating point number of degrees.
Latitudes in the Western hemisphere are expressed as negative numbers.
Parameters:
degrees latitude in degrees
References BVTNavData_SetLatitude().
RetVal BVTSDK::NavData::GetLongitude (double * degrees) [inline]
Returns the longitude.
If no longitude was stored, returns BVT_NAV_NO_DATA.
Parameters:
degrees longitude in degrees
References BVTNavData_GetLongitude().
RetVal BVTSDK::NavData::SetLongitude (double degrees) [inline]
Stores the longitude, as a signed floating point number of degrees.
Longitudes in the Southern hemisphere are expressed as negative numbers.
Parameters:
degrees longitude in degrees
References BVTNavData_SetLongitude().
RetVal BVTSDK::NavData::GetHorizontalPrecisionError (float * error_meters) [inline]
Returns the estimated horizontal error (see next function for details).
If none was stored, returns BVT_NAV_NO_DATA.
Parameters:
error_meters potential error distance, in meters
References BVTNavData_GetHorizontalPrecisionError().
RetVal BVTSDK::NavData::SetHorizontalPrecisionError (float error_meters) [inline]
Stores the estimated possible horizontal error.
This is primarily (but not exclusively) intended for GPS systems, where there may be some doubt as to the quality of the position fix. HDOP is common, but not used here, as that is a unitless measure and varies between different manufacturers and models.
The idea is to use whatever calculations are appropriate for the local navigation system, and store a possible error value in meters. Some GPS units will attempt to give this directly. (for example, the HPE field in the PGRME sentence, supplied by some Garmin units.) In the case of large errors, or old data, it may be best to either not store a position, or not store new data. (also consider using the NavData time parameter to store the time of last fix, which can then be compared to the ping time when the data is read back to determine the age of the GPS reading.)
Parameters:
error_meters potential error distance, in meters
References BVTNavData_SetHorizontalPrecisionError().
RetVal BVTSDK::NavData::GetHeight (float * meters_above_geoid) [inline]
Returns the height above mean sea level.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
meters_above_geoid height in floating point meters
References BVTNavData_GetHeight().
RetVal BVTSDK::NavData::SetHeight (float meters_above_geoid) [inline]
Store the height above Mean Sea Level (usually the EGM96 geoid)).
Parameters:
meters_above_geoid altitude in floating point meters
References BVTNavData_SetHeight().
RetVal BVTSDK::NavData::GetVerticalPrecisionError (float * error_meters) [inline]
Returns the estimated vertical error (see next function for details).
If none was stored, returns BVT_NAV_NO_DATA.
Parameters:
error_meters potential error distance, in meters
References BVTNavData_GetVerticalPrecisionError().
RetVal BVTSDK::NavData::SetVerticalPrecisionError (float error_meters) [inline]
Stores the estimated possible vertical error (height) above Mean Sea Level (EGM96 geoid).
For other notes, see the functions or Horizontal Precision Error, above.
Parameters:
error_meters potential error distance, in meters
References BVTNavData_SetVerticalPrecisionError().
RetVal BVTSDK::NavData::GetDepth (float * meters_below_surface) [inline]
Returns the depth.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
meters_below_surface depth in floating point meters
References BVTNavData_GetDepth().
RetVal BVTSDK::NavData::SetDepth (float meters_below_surface) [inline]
Store the depth.
Parameters:
meters_below_surface depth in floating point meters
References BVTNavData_SetDepth().
RetVal BVTSDK::NavData::GetAltitude (float * meters_above_bottom) [inline]
Returns the altitude.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
meters_above_bottom altitude in floating point meters
References BVTNavData_GetAltitude().
RetVal BVTSDK::NavData::SetAltitude (float meters_above_bottom) [inline]
Store the altitude.
Parameters:
meters_above_bottom altitude in floating point meters
References BVTNavData_SetAltitude().
RetVal BVTSDK::NavData::GetHeading (float * degrees_true) [inline]
Returns the heading relative to True North.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
degrees_true True heading, in degrees
References BVTNavData_GetHeading().
RetVal BVTSDK::NavData::SetHeading (float degrees_true) [inline]
Store the heading relative to True North.
Parameters:
degrees_true True heading, in degrees
References BVTNavData_SetHeading().
RetVal BVTSDK::NavData::GetHeadingVelocity (float * meters_per_second) [inline]
Returns the velocity along the heading.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
meters_per_second velocity, in meters per second
References BVTNavData_GetHeadingVelocity().
RetVal BVTSDK::NavData::SetHeadingVelocity (float meters_per_second) [inline]
Store the velocity along the heading.
Parameters:
meters_per_second velocity, in meters per second
References BVTNavData_SetHeadingVelocity().
RetVal BVTSDK::NavData::GetCourseOverGround (float * degrees_true) [inline]
Returns the course over ground (true).
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
degrees_true course over ground, true, in degrees
References BVTNavData_GetCourseOverGround().
RetVal BVTSDK::NavData::SetCourseOverGround (float degrees_true) [inline]
Store the course over ground, true.
Parameters:
degrees_true course over ground, true, in degrees
References BVTNavData_SetCourseOverGround().
RetVal BVTSDK::NavData::GetSpeedOverGround (float * meters_per_second) [inline]
Returns the speed over ground.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
meters_per_second speed over ground, in meters per second
References BVTNavData_GetSpeedOverGround().
RetVal BVTSDK::NavData::SetSpeedOverGround (float meters_per_second) [inline]
Store the speed over ground.
Parameters:
meters_per_second speed over ground, in meters per second
References BVTNavData_SetSpeedOverGround().
RetVal BVTSDK::NavData::GetPitchAngle (float * degrees_bow_up) [inline]
Get the pitch angle.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
degrees_bow_up pitch angle, in floating point degrees, bow up is positive
References BVTNavData_GetPitchAngle().
RetVal BVTSDK::NavData::SetPitchAngle (float degrees_bow_up) [inline]
Store the pitch angle.
Parameters:
degrees_bow_up pitch angle, in floating point degrees, bow up is positive
References BVTNavData_SetPitchAngle().
RetVal BVTSDK::NavData::GetRollAngle (float * degrees_port_up) [inline]
Get the roll angle.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
degrees_port_up roll angle, in floating point degrees, port side up is positive
References BVTNavData_GetRollAngle().
RetVal BVTSDK::NavData::SetRollAngle (float degrees_port_up) [inline]
Store the roll angle.
Parameters:
degrees_port_up roll angle, in floating point degrees, port side up is positive
References BVTNavData_SetRollAngle().
RetVal BVTSDK::NavData::GetYawAngle (float * degrees_bow_to_starboard) [inline]
Get the roll angle (but see notes with SetYawAngle()).
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
References BVTNavData_GetYawAngle().
RetVal BVTSDK::NavData::SetYawAngle (float degrees_bow_to_starboard) [inline]
Store the yaw angle.
NOTE: This is NOT the same as the Heading field. Heading is for the normal navigation use of Heading, often from a compass. This field is intended to store raw data from other research instruments, in case you need another storage spot. To keep everyone using the fields the same way so that files can be interchanged, please use SetHeading for the normal heading, and SetYawAngle() only for special uses.
References BVTNavData_SetYawAngle().
RetVal BVTSDK::NavData::GetPitchRate (float * degrees_per_second) [inline]
Returns the rate of pitch change.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
degrees_per_second rate of pitch change in degrees per second
References BVTNavData_GetPitchRate().
RetVal BVTSDK::NavData::SetPitchRate (float degrees_per_second) [inline]
Store the the rate of pitch change.
Parameters:
degrees_per_second rate of pitch change in degrees per second
References BVTNavData_SetPitchRate().
RetVal BVTSDK::NavData::GetRollRate (float * degrees_per_second) [inline]
Returns the rate of roll change.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
degrees_per_second rate of roll change in degrees per second
References BVTNavData_GetRollRate().
RetVal BVTSDK::NavData::SetRollRate (float degrees_per_second) [inline]
Store the the rate of change in roll.
Parameters:
degrees_per_second rate of roll change in floating point degrees per second
References BVTNavData_SetRollRate().
RetVal BVTSDK::NavData::GetYawRate (float * degrees_per_second) [inline]
Returns the rate of change in yaw (heading).
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
degrees_per_second rate of yaw change in floating point degrees per second
References BVTNavData_GetYawRate().
RetVal BVTSDK::NavData::SetYawRate (float degrees_per_second) [inline]
Store the rate of change in yaw (heading).
Parameters:
degrees_per_second rate of yaw change in floating point degrees per second
References BVTNavData_SetYawRate().
RetVal BVTSDK::NavData::GetAccelerationX (float * accel_mg) [inline]
Gets the stored acceleration along the X axis.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
accel_mg acceleration along X axis, in milli-g
References BVTNavData_GetAccelerationX().
RetVal BVTSDK::NavData::SetAccelerationX (float accel_mg) [inline]
Sets the stored acceleration along the X axis.
Intended to store raw values of accelerometers.
Parameters:
accel_mg acceleration along X axis, in milli-g
References BVTNavData_SetAccelerationX().
RetVal BVTSDK::NavData::GetAccelerationY (float * accel_mg) [inline]
Gets the stored acceleration along the Y axis.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
accel_mg acceleration along Y axis, in milli-g
References BVTNavData_GetAccelerationY().
RetVal BVTSDK::NavData::SetAccelerationY (float accel_mg) [inline]
Sets the stored acceleration along the Y axis.
Intended to store raw values of accelerometers.
Parameters:
accel_mg acceleration along Y axis, in milli-g
References BVTNavData_SetAccelerationY().
RetVal BVTSDK::NavData::GetAccelerationZ (float * accel_mg) [inline]
Gets the stored acceleration along the Z axis.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
accel_mg acceleration along Z axis, in milli-g
References BVTNavData_GetAccelerationZ().
RetVal BVTSDK::NavData::SetAccelerationZ (float accel_mg) [inline]
Sets the stored acceleration along the Z axis.
Intended to store raw values of accelerometers.
Parameters:
accel_mg acceleration along Z axis, in milli-g
References BVTNavData_SetAccelerationZ().
RetVal BVTSDK::NavData::GetOffsetNorth (double * meters) [inline]
Returns the offset, to the north, from a user-defined fixed point.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
meters offset to the north, in floating point meters
References BVTNavData_GetOffsetNorth().
RetVal BVTSDK::NavData::SetOffsetNorth (double meters) [inline]
Store the offset from a user-defined fixed point.
Parameters:
meters offset to the north, in floating point meters
References BVTNavData_SetOffsetNorth().
RetVal BVTSDK::NavData::GetOffsetEast (double * meters) [inline]
Returns the offset, to the east, from a user-defined fixed point.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
meters offset to the east, in floating point meters
References BVTNavData_GetOffsetEast().
RetVal BVTSDK::NavData::SetOffsetEast (double meters) [inline]
Store the offset from a user-defined fixed point.
Parameters:
meters offset to the east, in floating point meters
References BVTNavData_SetOffsetEast().
RetVal BVTSDK::NavData::GetOffsetIsFromLatLongFlag (int * is_true) [inline]
Gets a flag value which indicates if the East and North offset values are from the stored Latitude and Longitude.
(see more below...) If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
is_true either 1 or 0, to indicate true or false, respectively
References BVTNavData_GetOffsetIsFromLatLongFlag().
RetVal BVTSDK::NavData::SetOffsetIsFromLatLongFlag (int is_true) [inline]
Sets a flag to indicate if the East and North offset values are from the stored Latitude and Longitude.
If so, then software reading the file will know to adjust appropriately. If from some special location, perhaps the UserNavString could be used to indicate the reference point? If nothing is stored, then the value is assumed to be false.
Parameters:
is_true either 1 or 0, to indicate true or false, respectively
References BVTNavData_SetOffsetIsFromLatLongFlag().
std::string BVTSDK::NavData::GetUserNavString () [inline]
Returns the stored user string, in null-terminated form.
If no string was stored, returns a null string.
References BVTNavData_GetUserNavString().
RetVal BVTSDK::NavData::SetUserNavString (std::string string_in) [inline]
Stores a user-defined string related to navigation.
It is highly recommended to store some identifier such that the data is recognizable as you own.
Examples of possible uses might be to store locations based on coordinate systems other than GPS, indicating information about the use of the north and east offset parameters, additional fields from a GPS receiver, or any other information which might change dynamically.
Parameters:
string_in string to be stored, null terminated, max length 80 chars
References BVTNavData_SetUserNavString().
double BVTSDK::NavData::GetTimestamp () [inline]
Return the ping's timestamp in seconds since 00:00:00 UTC, January 1, 1970 Pings are timestamped using a standard UNIX time stamp.
This is a similar value to that returned by the time() C standard library function. In fact, the only difference is the addition of fractional seconds.
References BVTNavData_GetTimestamp().
RetVal BVTSDK::NavData::SetTimestamp (double sec) [inline]
Set the NavData's internal time stamp.
See GetTimestamp() for more information.
Parameters:
sec Timestamp in seconds since 00:00:00 UTC, January 1, 1970
References BVTNavData_SetTimestamp().