ProViewer SDK: BVTSDK::MagImage Class Reference
BVTSDK::MagImage Class Reference
MagImage is short for MagnitudeImage.
Public Member Functions
MagImage ()
~MagImage ()
int GetHeight ()
int GetWidth ()
double GetRangeResolution ()
double GetBearingResolution ()
int GetOriginRow ()
int GetOriginCol ()
double GetPixelRange (int row, int col)
double GetPixelRelativeBearing (int row, int col)
double GetFOVMinAngle ()
double GetFOVMaxAngle ()
unsigned short GetPixel (int row, int col)
unsigned short * GetRow (int row)
unsigned short * GetBits ()
RetVal CopyBits (unsigned short *data, unsigned int len)
RetVal SavePGM (std::string file_name)
Detailed Description
MagImage is short for MagnitudeImage.
It provides access to a 2d image where each pixel is intensity of the return from a particular point on a plane emanating from the head. It can be thought of as a 16bit grey-scale image.
Constructor & Destructor Documentation
BVTSDK::MagImage::MagImage () [inline]
Create the object.
BVTSDK::MagImage::~MagImage () [inline]
Destroy the object.
References BVTMagImage_Destroy().
Member Function Documentation
int BVTSDK::MagImage::GetHeight () [inline]
Return the height (in pixels) of this image.
References BVTMagImage_GetHeight().
int BVTSDK::MagImage::GetWidth () [inline]
Return the width (in pixels) of this image.
References BVTMagImage_GetWidth().
double BVTSDK::MagImage::GetRangeResolution () [inline]
Return the range resolution of this image.
The resolution is returned in meters per pixel.
References BVTMagImage_GetRangeResolution().
double BVTSDK::MagImage::GetBearingResolution () [inline]
Only valid for R-Theta images.
Returns the bearing resolution, in degrees per column.
References BVTMagImage_GetBearingResolution().
int BVTSDK::MagImage::GetOriginRow () [inline]
Retrieve the image row of the origin.
In most cases the origin will be outside of the image boundaries. The origin is the 'location' (in pixels) of the sonar head in image plane
References BVTMagImage_GetOriginRow().
int BVTSDK::MagImage::GetOriginCol () [inline]
Retrieve the image column of the origin.
In most cases the origin will be outside of the image boundaries. The origin is the 'location' (in pixels) of the sonar head in image plane
References BVTMagImage_GetOriginCol().
double BVTSDK::MagImage::GetPixelRange (int row, int col) [inline]
Retrieve the range (from the sonar head) of the specified pixel.
Parameters:
row Origin row
col Origin col
References BVTMagImage_GetPixelRange().
double BVTSDK::MagImage::GetPixelRelativeBearing (int row, int col) [inline]
Retrieve the bearing relative to the sonar head of the specified pixel.
Parameters:
row Origin row
col Origin col
References BVTMagImage_GetPixelRelativeBearing().
double BVTSDK::MagImage::GetFOVMinAngle () [inline]
Return the minimum angle for the sonar's imaging field of view.
The angle is returned in degrees.
References BVTMagImage_GetFOVMinAngle().
double BVTSDK::MagImage::GetFOVMaxAngle () [inline]
Return the maximum angle for the sonar's imaging field of view.
The angle is returned in degrees.
References BVTMagImage_GetFOVMaxAngle().
unsigned short BVTSDK::MagImage::GetPixel (int row, int col) [inline]
Return the value of the pixel at (row, col).
Parameters:
row Requested row
col Requested col
References BVTMagImage_GetPixel().
unsigned short* BVTSDK::MagImage::GetRow (int row) [inline]
Return a pointer to a row of pixels.
Parameters:
row Requested row
References BVTMagImage_GetRow().
unsigned short* BVTSDK::MagImage::GetBits () [inline]
Return a pointer to the entire image.
The image or organized in Row-Major order (just like C/C++).
References BVTMagImage_GetBits().
RetVal BVTSDK::MagImage::CopyBits (unsigned short * data, unsigned int len) [inline]
Copy the raw image data to the user specified buffer.
See GetBits for more info.
Parameters:
data Pointer to a valid buffer
len The size of the buffer pointed to by data in pixels NOT bytes.
References BVTMagImage_CopyBits().
RetVal BVTSDK::MagImage::SavePGM (std::string file_name) [inline]
Save the image in PGM (PortableGreyMap) format.
Note that few programs actually support loading a 16bit PGM.
Parameters:
file_name File name to save to
References BVTMagImage_SavePGM().