ProViewer SDK: BVTSDK::RangeData Class Reference
BVTSDK::RangeData Class Reference
** EXPERIMENTAL ** This functionality is still under development! *** RangeData is a set of ranges from the sonar head, at various angles from the sonar head.
Public Member Functions
RangeData ()
int GetCount ()
double GetRangeResolution ()
double GetBearingResolution ()
float GetFOVMinAngle ()
float GetFOVMaxAngle ()
RetVal CopyRangeValues (float *ranges, int number_of_ranges)
float GetRangeValue (int index)
float GetBearingValue (int index)
int GetColorImagePixelX (int rangeDataIndex, const ColorImage &image)
int GetColorImagePixelY (int rangeDataIndex, const ColorImage &image)
Static Public Attributes
static const int MAX_RANGE = 999
Detailed Description
** EXPERIMENTAL ** This functionality is still under development! *** RangeData is a set of ranges from the sonar head, at various angles from the sonar head.
For each angle, the range, bearing and intensity of the return beam at that range is stored. NOTE: RangeData only applies to specialized BlueView sonars, and has no use for our standard imaging sonars.
Constructor & Destructor Documentation
BVTSDK::RangeData::RangeData () [inline]
Create the object.
Member Function Documentation
int BVTSDK::RangeData::GetCount () [inline]
Returns the number of range values stored for this ping.
References BVTRangeData_GetCount().
double BVTSDK::RangeData::GetRangeResolution () [inline]
Returns the resolution of the range values, in meters.
References BVTRangeData_GetRangeResolution().
double BVTSDK::RangeData::GetBearingResolution () [inline]
Returns the resolution of the bearing stored with each range value.
This is the difference in bearing between each range value in the array.
References BVTRangeData_GetBearingResolution().
float BVTSDK::RangeData::GetFOVMinAngle () [inline]
Return the minimum angle for the sonar's imaging field of view.
In other words, this is the angle of the first range value, as all angles are "left referenced."The angle is returned in degrees. Note that this may not represent the actual physical field of view of a particular sonar, but does represent the field of view of the data being returned. Some outside values may have range values indicating they are out of range.
References BVTRangeData_GetFOVMinAngle().
float BVTSDK::RangeData::GetFOVMaxAngle () [inline]
Return the maximum angle for the sonar's imaging field of view.
In other words, this is the angle of the last range value, as all angles are "left referenced."The angle is returned in degrees. Note that this may not represent the actual physical field of view of a particular sonar, but does represent the field of view of the data being returned. Some outside values may have range values indicating they are out of range.
References BVTRangeData_GetFOVMaxAngle().
RetVal BVTSDK::RangeData::CopyRangeValues (float * ranges, int number_of_ranges) [inline]
Copies the range values into the user specified buffer.
The buffer must hold the entire number of ranges (See GetCount() above), or an error is returned.
Parameters:
ranges Pointer to a valid buffer of type float.
number_of_ranges Number of values the buffer can hold.
References BVTRangeData_CopyRangeValues().
float BVTSDK::RangeData::GetRangeValue (int index) [inline]
Returns the range from the sonar head, in meters, at a particular index into the array.
NOTE: Check all returned values for validity. If range > BVTRANGEDATA_MAX_RANGE then the range could not be determined within the capabilities of the sonar. Meaning that the closest object at that bearing was either out of view of the sonar, or the threshold was set too high to be detected.
Parameters:
index index into the array of RangeData values
References BVTRangeData_GetRangeValue().
float BVTSDK::RangeData::GetBearingValue (int index) [inline]
Returns the bearing from the center of the sonar head, in degrees (+/-), at a particular index into the array.
Parameters:
index index into the array of RangeData values
References BVTRangeData_GetBearingValue().
int BVTSDK::RangeData::GetColorImagePixelX (int rangeDataIndex, const ColorImage & image) [inline]
Returns the X coordinate for the pixel in the passed ColorImage, which maps to the range and bearing at the index passed.
This allows placing of the range data on a colorimage, easing analysis of the algorithm used for thresholding.
Parameters:
image ColorImage object where the pixel coordinate is needed
References BVTRangeData_GetColorImagePixelX().
int BVTSDK::RangeData::GetColorImagePixelY (int rangeDataIndex, const ColorImage & image) [inline]
Returns the Y coordinate for the pixel in the passed ColorImage which maps to the range and bearing at the index passed.
(see similar function, above, for more details)
Parameters:
image ColorImage object where the pixel coordinate is needed
References BVTRangeData_GetColorImagePixelY().
Field Documentation
const int BVTSDK::RangeData::MAX_RANGE = 999 [static]
Values greater than this indicate no range could be measured.