ProViewer SDK: BVTSDK::Sonar Class Reference
BVTSDK::Sonar Class Reference
The Sonar object is the top level object in the SDK.
Public Member Functions
Sonar ()
~Sonar ()
RetVal Open (std::string type, std::string type_params)
RetVal CreateFile (std::string file_name, const Sonar &src, std::string create_params)
int GetFileSize ()
RetVal GetHead (int head_num, Head *head)
int GetHeadCount ()
RetVal GetSonarTypeAsString (char *buffer, int buffer_size)
RetVal GetSonarName (char *buffer, int buffer_size)
float GetTemperature ()
Detailed Description
The Sonar object is the top level object in the SDK.
A sonar object embodies communication with a single physical sonar unit, or file. Each sonar contains several heads, which is where most of the functionality is implemented. Sonar also provides a function to create new data files using BlueView's .son format.
Constructor & Destructor Documentation
BVTSDK::Sonar::Sonar () [inline]
Create the object.
References BVTSonar_Create().
BVTSDK::Sonar::~Sonar () [inline]
Destroy the object.
References BVTSonar_Destroy().
Member Function Documentation
RetVal BVTSDK::Sonar::Open (std::string type, std::string type_params) [inline]
Open the sonar type 'type' using the specified parameters.
Allowed types (and parameters):
FILE
[filename] - Required
NET
[host] - Connect to the specified host.
Parameters:
type The type of sonar to open
type_params Various type-specific parameters
References BVTSonar_Open().
RetVal BVTSDK::Sonar::CreateFile (std::string file_name, const Sonar & src, std::string create_params) [inline]
Create a new data file.
Files are always created by 'cloning' another Sonar object. This ensures that the file receives all the needed setup/configuration data needed to process images.
Parameters:
file_name The filename of the file to be created
src The Sonar object to clone when creating the file
create_params Parameters for (reserved for future use)
References BVTSonar_CreateFile().
int BVTSDK::Sonar::GetFileSize () [inline]
Gets the size of a file created with CreateFile().
Only works with file type sonars. A networked sonar will return 0, as will a file type sonar if there is no open file associated with it. The return value must be multiplied by 1000 to get the actual file size in bytes.
References BVTSonar_GetFileSize().
RetVal BVTSDK::Sonar::GetHead (int head_num, Head * head) [inline]
Retrieve a Head object from the sonar.
Parameters:
head_num The head number to return
head The returned Head object
References BVTSonar_GetHead().
int BVTSDK::Sonar::GetHeadCount () [inline]
Return the number of heads on this sonar.
References BVTSonar_GetHeadCount().
RetVal BVTSDK::Sonar::GetSonarTypeAsString (char * buffer, int buffer_size) [inline]
Retrieves a copy of a short string with the model of the sonar.
At the time of this writing, 20 characters would easily hold all of the sonar model names.
Parameters:
buffer buffer to hold the null-terminated string to be passed back
buffer_size total number of characters the passed buffer can hold
References BVTSonar_GetSonarTypeAsString().
RetVal BVTSDK::Sonar::GetSonarName (char * buffer, int buffer_size) [inline]
Retrieves a copy of the name of the sonar.
The name is set only via the ProViewer application (at least at this time), or at the factory, and is separate from any BlueView model designations.
The length of the name could be considerably longer than the sonar type, and there is no actual limit, though 80 characters would seem to be more than enough.
Parameters:
buffer buffer to hold the null-terminated string to be passed back
buffer_size total number of characters the passed buffer can hold
References BVTSonar_GetSonarName().
float BVTSDK::Sonar::GetTemperature () [inline]
Return the sonar's internal temperature in degrees Celsius If the sonar doesn't have a temp sensor this function returns absolute zero (-273.15).
References BVTSonar_GetTemperature().