ProViewer SDK: BVTSDK::ColorMapper Class Reference
BVTSDK::ColorMapper Class Reference
Provide support for applying a colormap to a MagImage, thus generating a ColorImage.
Public Member Functions
ColorMapper ()
~ColorMapper ()
RetVal Load (std::string file)
RetVal SetGamma (float gamma)
float GetGamma ()
RetVal SetThresholds (int top, int bottom)
int GetTopThreshold ()
int GetBottomThreshold ()
int GetAutoMode ()
RetVal SetAutoMode (int mode)
RetVal MapImage (const MagImage &input, ColorImage *output)
Detailed Description
Provide support for applying a colormap to a MagImage, thus generating a ColorImage.
Constructor & Destructor Documentation
BVTSDK::ColorMapper::ColorMapper () [inline]
Create the object.
References BVTColorMapper_Create().
BVTSDK::ColorMapper::~ColorMapper () [inline]
Destroy the object.
References BVTColorMapper_Destroy().
Member Function Documentation
RetVal BVTSDK::ColorMapper::Load (std::string file) [inline]
Load a color map file.
Parameters:
file Colormap file name
References BVTColorMapper_Load().
RetVal BVTSDK::ColorMapper::SetGamma (float gamma) [inline]
Set the gamma used when colormapping.
Parameters:
gamma Gamma value
References BVTColorMapper_SetGamma().
float BVTSDK::ColorMapper::GetGamma () [inline]
Return the current gamma.
References BVTColorMapper_GetGamma().
RetVal BVTSDK::ColorMapper::SetThresholds (int top, int bottom) [inline]
Set the intensity values to be mapped to the top and bottom of the colormap.
If auto intensity is enabled, this function returns an error.
Parameters:
top Top colormap threshold (aka intensity)
bottom Bottom colormap threshold
References BVTColorMapper_SetThresholds().
int BVTSDK::ColorMapper::GetTopThreshold () [inline]
Return the upper threshold for the colormap.
The top threshold is also known as 'intensity'. Lowering the top threshold will make a brighter image.
References BVTColorMapper_GetTopThreshold().
int BVTSDK::ColorMapper::GetBottomThreshold () [inline]
Return the lower threshold for the colormap.
References BVTColorMapper_GetBottomThreshold().
int BVTSDK::ColorMapper::GetAutoMode () [inline]
Return a number greater than 0 if auto-threshold is enabled, 0 if it's not.
References BVTColorMapper_GetAutoMode().
RetVal BVTSDK::ColorMapper::SetAutoMode (int mode) [inline]
Enable or disable an internal auto-threshold algorithm.
Parameters:
mode > 0 if auto-threshold should be enabled. 0 otherwise.
References BVTColorMapper_SetAutoMode().
RetVal BVTSDK::ColorMapper::MapImage (const MagImage & input, ColorImage * output) [inline]
Colormap an image.
Parameters:
input Input magnitude image
output Output color image
References BVTColorMapper_MapImage().