ProViewer SDK: BVTSDK::Head Class Reference
BVTSDK::Head Class Reference
A head consists of a group of co-planar transducers which are operated simultaneously to produce (ultimately) a single 2d image.
Public Member Functions
Head ()
RetVal GetHeadName (char *buffer, int buffer_size)
RetVal SetRange (float start, float stop)
float GetStartRange ()
float GetStopRange ()
float GetMinimumRange ()
float GetMaximumRange ()
int GetFluidType ()
RetVal SetFluidType (int fluid)
int GetSoundSpeed ()
RetVal SetSoundSpeed (int speed)
float GetGainAdjustment ()
RetVal SetGainAdjustment (float gain)
float GetTVGSlope ()
RetVal SetTVGSlope (float tvg)
int GetCenterFreq ()
int GetPingCount ()
RetVal GetPing (int ping_num, Ping *ping)
RetVal PutPing (const Ping &ping)
RetVal SetImageRes (int res)
RetVal SetRangeResolution (float resolution_in_meters)
RetVal SetImageReqSize (int height, int width)
RetVal SetRemoteBeamForming (int enable)
RetVal SetRawDataSending (int enable)
RetVal SetRemoteImageForming (int enable)
RetVal SetImageType (int type)
int GetImageFilterFlags ()
RetVal SetImageFilterFlags (int flags)
RetVal SetRangeDataThreshold (unsigned short noise_threshold)
RetVal SetTxEnable (int enableTx)
RetVal GetMountingOrientation (double *X_axis_degrees, double *Y_axis_degrees, double *Z_axis_degrees)
RetVal SetMountingOrientation (double X_axis_degrees, double Y_axis_degrees, double Z_axis_degrees)
Static Public Attributes
static const int FLUID_SALTWATER = 0
static const int FLUID_FRESHWATER = 1
static const int FLUID_OTHER = 2
static const int RES_OFF = 0
static const int RES_LOW = 1
static const int RES_MED = 2
static const int RES_HIGH = 3
static const int RES_AUTO = 4
static const int IMAGE_XY = 0
static const int IMAGE_RTHETA = 1
Detailed Description
A head consists of a group of co-planar transducers which are operated simultaneously to produce (ultimately) a single 2d image.
The Head object provides functions to change the range window as well as produce pings.
Constructor & Destructor Documentation
BVTSDK::Head::Head () [inline]
Create the object.
Member Function Documentation
RetVal BVTSDK::Head::GetHeadName (char * buffer, int buffer_size) [inline]
Retrieves a copy of a the name of the head.
The head name is currently set only at the factory, and is simply "Head" on many sonars. Only special order sonars with multiple heads are likely to have a different name.
The length of the name has no actual limit, though 80 characters would seem to be more than enough.
Parameters:
buffer buffer to hold the null-terminated string to be passed back
buffer_size total number of characters the passed buffer can hold
References BVTHead_GetHeadName().
RetVal BVTSDK::Head::SetRange (float start, float stop) [inline]
Set the range to be acquired.
Parameters:
start Start range in meters
stop Stop range in meters
References BVTHead_SetRange().
float BVTSDK::Head::GetStartRange () [inline]
Retrieve the current starting range in meters.
References BVTHead_GetStartRange().
float BVTSDK::Head::GetStopRange () [inline]
Retrieve the current stopping range in meters.
References BVTHead_GetStopRange().
float BVTSDK::Head::GetMinimumRange () [inline]
Return the minimum allowable range for this sonar.
References BVTHead_GetMinimumRange().
float BVTSDK::Head::GetMaximumRange () [inline]
Return the maximum allowable range for this sonar.
References BVTHead_GetMaximumRange().
int BVTSDK::Head::GetFluidType () [inline]
Return the type of water the head is in.
The returned value will correspond to one of the FLUID_* constants.
References BVTHead_GetFluidType().
RetVal BVTSDK::Head::SetFluidType (int fluid) [inline]
Set the type of water the head is in.
Parameters:
fluid The fluid type (one of the FLUID_* constants)
References BVTHead_SetFluidType().
int BVTSDK::Head::GetSoundSpeed () [inline]
Return the speed of sound in water.
References BVTHead_GetSoundSpeed().
RetVal BVTSDK::Head::SetSoundSpeed (int speed) [inline]
Set the speed of sound in water.
Parameters:
speed Sound speed in water
References BVTHead_SetSoundSpeed().
float BVTSDK::Head::GetGainAdjustment () [inline]
Return the additional analog gain in dB.
References BVTHead_GetGainAdjustment().
RetVal BVTSDK::Head::SetGainAdjustment (float gain) [inline]
Set the additional analog gain.
Note: Some systems don't support gain adjustment.
Parameters:
gain Additional analog gain in dB
References BVTHead_SetGainAdjustment().
float BVTSDK::Head::GetTVGSlope () [inline]
Return the time variable gain in dB/meter.
References BVTHead_GetTVGSlope().
RetVal BVTSDK::Head::SetTVGSlope (float tvg) [inline]
Set the time variable analog gain.
Note: Some systems don't support TVG
Parameters:
tvg Time variable gain in dB/meter
References BVTHead_SetTVGSlope().
int BVTSDK::Head::GetCenterFreq () [inline]
Return the center frequency(in Hz) of this head.
References BVTHead_GetCenterFreq().
int BVTSDK::Head::GetPingCount () [inline]
Return the number of pings 'in' this head A head attached to a file might have more than one ping recorded.
However, a networked sonar will only have a single ping.
References BVTHead_GetPingCount().
RetVal BVTSDK::Head::GetPing (int ping_num, Ping * ping) [inline]
Retrieve a Ping from the Head If ping_num is less than 0, return the next ping in the file.
Otherwise, load the specified ping. If the Head is attached to a 'live' sonar (network), then GetPing always acquires a new ping.
Parameters:
ping_num The ping number to return
ping The returned Ping object
References BVTHead_GetPing().
RetVal BVTSDK::Head::PutPing (const Ping & ping) [inline]
Write a ping to a file.
Parameters:
ping The ping to write out
References BVTHead_PutPing().
RetVal BVTSDK::Head::SetImageRes (int res) [inline]
Set the image processing resolution.
The RES_AUTO setting is highly recommended, as it adapts via a formula according to the stop range, whereas the other ranges are fixed values, and should only be used in specialized cases, such as requesting high resolution for longer distances (which will increase the processing time required to create the image). R-Theta images may use either this funtion or SetRangeResolution(), depending on the degree of control required.
Parameters:
res Resolution constant (RES_*)
References BVTHead_SetImageRes().
RetVal BVTSDK::Head::SetRangeResolution (float resolution_in_meters) [inline]
Requests a range resolution for R-Theta images.
Also affects the range resolution for RangeData. Note that the exact range resolution may not be available, and the closest resolution will be set. The actual resolution can be obtained by querying the returned image or RangeData object.
Parameters:
resolution_in_meters Range resolution, in meters
References BVTHead_SetRangeResolution().
RetVal BVTSDK::Head::SetImageReqSize (int height, int width) [inline]
Set the requested out image size The processing code will attempt to process images at the specified size.
However, it doesn't guarantee that the final output will match this size. NOTE: For R-Theta images, only the width is used, and the image will be created with that exact width. Height will depend on the range, and the resolution set. (See SetImageRes() and SetRangeResolution())
Parameters:
height The requested height
width The requested width
References BVTHead_SetImageReqSize().
RetVal BVTSDK::Head::SetRemoteBeamForming (int enable) [inline]
NOTE: this option is only valid for some sonars, in specific circumstances, and should only be used on advice from the factory.
By default, beamforming is done on the local system. If you call this function with enable=true, the SDK will request that the remote sonar handle the majority of the beamforming. This operation applies the next time GetPing is called.
Parameters:
enable Enable/Disable remote beamformer. (using 1 or 0 to enable or disable)
References BVTHead_SetRemoteBeamForming().
RetVal BVTSDK::Head::SetRawDataSending (int enable) [inline]
NOTE: this option is only valid for some sonars, in specific circumstances, and should only be used on advice from the factory.
By default, the sonar sends data suitable for saving to a .son file. If you are not saving files, AND are recieving processed data thru setting one of the other options, you can call this function with enable=false to reduce the amount of network bandwidth needed. . This operation applies the next time GetPing is called.
Parameters:
enable Enable/Disable raw ping data. (using 1 or 0 to enable or disable)
References BVTHead_SetRawDataSending().
RetVal BVTSDK::Head::SetRemoteImageForming (int enable) [inline]
NOTE: this option is only valid for some sonars, in specific circumstances, and should only be used on advice from the factory.
By default, image forming is done on the local system. If you call this function with en=true, the SDK will request that the remote sonar handle the image forming. This option is slightly different than remote beam-forming, with all processing done on the sonar, and only the complete image sent over the network connection. This operation applies the next time GetPing is called.
Parameters:
enable Enable/Disable remote image forming. (using 1 or 0 to enable or disable)
References BVTHead_SetRemoteImageForming().
RetVal BVTSDK::Head::SetImageType (int type) [inline]
Set the type of image output.
NOTE: See SetImageReqSize() for important issues regarding image size.
Parameters:
type Image type constant (IMAGE_*)
References BVTHead_SetImageType().
int BVTSDK::Head::GetImageFilterFlags () [inline]
Return the filter flags.
References BVTHead_GetImageFilterFlags().
RetVal BVTSDK::Head::SetImageFilterFlags (int flags) [inline]
Set the filter flags.
Parameters:
flags Image filter flags (bit field)
References BVTHead_SetImageFilterFlags().
RetVal BVTSDK::Head::SetRangeDataThreshold (unsigned short noise_threshold) [inline]
** EXPERIMENTAL ** Sets the intensity value below which data is considered to be noise.
Values above this threshold are included in the algorithm which attempts to determine the target edge. This is NOT a simple threshold above which the first value encountered is considered the target edge. This is the same intensity value returned in a MagImage, with a range of an unsigned 16-bit integer. If not set, the default is currently set to 1000.
NOTE: This only applies to specialized BlueView sonars.
Parameters:
noise_threshold Threshold below which is considered noise
References BVTHead_SetRangeDataThreshold().
RetVal BVTSDK::Head::SetTxEnable (int enableTx) [inline]
By default, the sonar transmits pings.
This function allows the user to disable transmit. This can be useful to get background noise measurements. Note that this is not implemented on all sonars.
Parameters:
enableTx If 0, disable the sonar transmission of pings.
References BVTHead_SetTxEnable().
RetVal BVTSDK::Head::GetMountingOrientation (double * X_axis_degrees, double * Y_axis_degrees, double * Z_axis_degrees) [inline]
** Preliminary support - may change in later SDK versions **
Position of the sonar positioner relative to the boat.
Parameters:
X_axis_degrees rotation about X axis
Y_axis_degrees rotation about Y axis
Z_axis_degrees rotation about Z axis
References BVTHead_GetMountingOrientation().
RetVal BVTSDK::Head::SetMountingOrientation (double X_axis_degrees, double Y_axis_degrees, double Z_axis_degrees) [inline]
** Preliminary support - may change in later SDK versions **
Position of the sonar positioner relative to the boat.
Parameters:
X_axis_degrees rotation about X axis
Y_axis_degrees rotation about Y axis
Z_axis_degrees rotation about Z axis
References BVTHead_SetMountingOrientation().
Field Documentation
const int BVTSDK::Head::FLUID_SALTWATER = 0 [static]
const int BVTSDK::Head::FLUID_FRESHWATER = 1 [static]
const int BVTSDK::Head::FLUID_OTHER = 2 [static]
const int BVTSDK::Head::RES_OFF = 0 [static]
Turn off image processing.
const int BVTSDK::Head::RES_LOW = 1 [static]
Process at low resolution.
const int BVTSDK::Head::RES_MED = 2 [static]
Process at med resolution.
const int BVTSDK::Head::RES_HIGH = 3 [static]
Process at high resolution.
const int BVTSDK::Head::RES_AUTO = 4 [static]
Select a good res for the current range automatically.
const int BVTSDK::Head::IMAGE_XY = 0 [static]
Output a cartesian image.
const int BVTSDK::Head::IMAGE_RTHETA = 1 [static]
Output a Range/Theta image.