ProViewer SDK: BVTSDK::ColorImage Class Reference
BVTSDK::ColorImage Class Reference
Store a color image.
Public Member Functions
ColorImage ()
~ColorImage ()
int GetHeight ()
int GetWidth ()
double GetRangeResolution ()
int GetOriginRow ()
int GetOriginCol ()
double GetPixelRange (int row, int col)
double GetPixelRelativeBearing (int row, int col)
double GetFOVMinAngle ()
double GetFOVMaxAngle ()
unsigned int GetPixel (int row, int col)
unsigned int * GetRow (int row)
unsigned int * GetBits ()
RetVal CopyBits (unsigned int *data, unsigned int len)
RetVal SavePPM (std::string file_name)
Detailed Description
Store a color image.
The API is nearly identical to MagImage. The main difference is the pixel datatype. In ColorImage, each pixel is a single unsigned int.
Byte 0: Red Value
Byte 1: Green Value
Byte 2: Blue Value
Byte 3: Alpha Value
Constructor & Destructor Documentation
BVTSDK::ColorImage::ColorImage () [inline]
Create the object.
BVTSDK::ColorImage::~ColorImage () [inline]
Destroy the object.
References BVTColorImage_Destroy().
Member Function Documentation
int BVTSDK::ColorImage::GetHeight () [inline]
Return the height (in pixels) of this image.
References BVTColorImage_GetHeight().
int BVTSDK::ColorImage::GetWidth () [inline]
Return the width (in pixels) of this image.
References BVTColorImage_GetWidth().
double BVTSDK::ColorImage::GetRangeResolution () [inline]
Return the range resolution of this image.
The resolution is returned in meters per pixel
References BVTColorImage_GetRangeResolution().
int BVTSDK::ColorImage::GetOriginRow () [inline]
Retrieve the image row of the origin.
In most cases the origin will be outside of the image boundaries. The origin is the 'location' (in pixels) of the sonar head in image plane
References BVTColorImage_GetOriginRow().
int BVTSDK::ColorImage::GetOriginCol () [inline]
Retrieve the image column of the origin.
In most cases the origin will be outside of the image boundaries. The origin is the 'location' (in pixels) of the sonar head in image plane
References BVTColorImage_GetOriginCol().
double BVTSDK::ColorImage::GetPixelRange (int row, int col) [inline]
Retrieve the range (from the sonar head) of the specified pixel.
Parameters:
row Origin row
col Origin col
References BVTColorImage_GetPixelRange().
double BVTSDK::ColorImage::GetPixelRelativeBearing (int row, int col) [inline]
Retrieve the bearing relative to the sonar head of the specified pixel.
Parameters:
row Origin row
col Origin col
References BVTColorImage_GetPixelRelativeBearing().
double BVTSDK::ColorImage::GetFOVMinAngle () [inline]
Return the minimum angle for the sonar's imaging field of view.
The angle is returned in degrees.
References BVTColorImage_GetFOVMinAngle().
double BVTSDK::ColorImage::GetFOVMaxAngle () [inline]
Return the maximum angle for the sonar's imaging field of view.
The angle is returned in degrees.
References BVTColorImage_GetFOVMaxAngle().
unsigned int BVTSDK::ColorImage::GetPixel (int row, int col) [inline]
Return the value of the pixel at (row, col).
Parameters:
row Requested row
col Requested col
References BVTColorImage_GetPixel().
unsigned int* BVTSDK::ColorImage::GetRow (int row) [inline]
Return a pointer to a row of pixels.
Parameters:
row Requested row
References BVTColorImage_GetRow().
unsigned int* BVTSDK::ColorImage::GetBits () [inline]
Return a pointer to the entire image.
The image or organized in Row-Major order (just like C/C++).
References BVTColorImage_GetBits().
RetVal BVTSDK::ColorImage::CopyBits (unsigned int * data, unsigned int len) [inline]
Copy the raw image data to the user specified buffer.
See GetBits for more info.
Parameters:
data Pointer to a valid buffer
len The size of the buffer pointed to by data in pixels NOT bytes.
References BVTColorImage_CopyBits().
RetVal BVTSDK::ColorImage::SavePPM (std::string file_name) [inline]
Save the image in PPM (PortablePixMap) format.
Parameters:
file_name File name to save to
References BVTColorImage_SavePPM().