ProViewer SDK: BVTSDK::SDK Class Reference
BVTSDK::SDK Class Reference
Static Public Member Functions
static int MajorVersion ()
static int MinorVersion ()
static int BuildNumber ()
Member Function Documentation
static int BVTSDK::SDK::MajorVersion () [inline, static]
Return the major version number of the SDK.
References BVTSDK_MajorVersion().
static int BVTSDK::SDK::MinorVersion () [inline, static]
Return the minor version of the SDK.
References BVTSDK_MinorVersion().
static int BVTSDK::SDK::BuildNumber () [inline, static]
Return the build number of the SDK.
References BVTSDK_BuildNumber().