ProViewer SDK: BVTNavData Object
BVTNavData Object
NavData contains various types of user-accessible navigation parameter, which can be saved to and retrieved from a sonar file on a per ping basis.
Typedefs
typedef void * BVTNavData
Functions
BVTNavData BVTNavData_Create ()
void BVTNavData_Destroy (BVTNavData obj)
RetVal BVTNavData_Clone (BVTNavData obj, const BVTNavData navdata_to_clone)
RetVal BVTNavData_GetLatitude (BVTNavData obj, double *degrees)
RetVal BVTNavData_SetLatitude (BVTNavData obj, double degrees)
RetVal BVTNavData_GetLongitude (BVTNavData obj, double *degrees)
RetVal BVTNavData_SetLongitude (BVTNavData obj, double degrees)
RetVal BVTNavData_GetHorizontalPrecisionError (BVTNavData obj, float *error_meters)
RetVal BVTNavData_SetHorizontalPrecisionError (BVTNavData obj, float error_meters)
RetVal BVTNavData_GetHeight (BVTNavData obj, float *meters_above_geoid)
RetVal BVTNavData_SetHeight (BVTNavData obj, float meters_above_geoid)
RetVal BVTNavData_GetVerticalPrecisionError (BVTNavData obj, float *error_meters)
RetVal BVTNavData_SetVerticalPrecisionError (BVTNavData obj, float error_meters)
RetVal BVTNavData_GetDepth (BVTNavData obj, float *meters_below_surface)
RetVal BVTNavData_SetDepth (BVTNavData obj, float meters_below_surface)
RetVal BVTNavData_GetAltitude (BVTNavData obj, float *meters_above_bottom)
RetVal BVTNavData_SetAltitude (BVTNavData obj, float meters_above_bottom)
RetVal BVTNavData_GetHeading (BVTNavData obj, float *degrees_true)
RetVal BVTNavData_SetHeading (BVTNavData obj, float degrees_true)
RetVal BVTNavData_GetHeadingVelocity (BVTNavData obj, float *meters_per_second)
RetVal BVTNavData_SetHeadingVelocity (BVTNavData obj, float meters_per_second)
RetVal BVTNavData_GetCourseOverGround (BVTNavData obj, float *degrees_true)
RetVal BVTNavData_SetCourseOverGround (BVTNavData obj, float degrees_true)
RetVal BVTNavData_GetSpeedOverGround (BVTNavData obj, float *meters_per_second)
RetVal BVTNavData_SetSpeedOverGround (BVTNavData obj, float meters_per_second)
RetVal BVTNavData_GetPitchAngle (BVTNavData obj, float *degrees_bow_up)
RetVal BVTNavData_SetPitchAngle (BVTNavData obj, float degrees_bow_up)
RetVal BVTNavData_GetRollAngle (BVTNavData obj, float *degrees_port_up)
RetVal BVTNavData_SetRollAngle (BVTNavData obj, float degrees_port_up)
RetVal BVTNavData_GetYawAngle (BVTNavData obj, float *degrees_bow_to_starboard)
RetVal BVTNavData_SetYawAngle (BVTNavData obj, float degrees_bow_to_starboard)
RetVal BVTNavData_GetPitchRate (BVTNavData obj, float *degrees_per_second)
RetVal BVTNavData_SetPitchRate (BVTNavData obj, float degrees_per_second)
RetVal BVTNavData_GetRollRate (BVTNavData obj, float *degrees_per_second)
RetVal BVTNavData_SetRollRate (BVTNavData obj, float degrees_per_second)
RetVal BVTNavData_GetYawRate (BVTNavData obj, float *degrees_per_second)
RetVal BVTNavData_SetYawRate (BVTNavData obj, float degrees_per_second)
RetVal BVTNavData_GetAccelerationX (BVTNavData obj, float *accel_mg)
RetVal BVTNavData_SetAccelerationX (BVTNavData obj, float accel_mg)
RetVal BVTNavData_GetAccelerationY (BVTNavData obj, float *accel_mg)
RetVal BVTNavData_SetAccelerationY (BVTNavData obj, float accel_mg)
RetVal BVTNavData_GetAccelerationZ (BVTNavData obj, float *accel_mg)
RetVal BVTNavData_SetAccelerationZ (BVTNavData obj, float accel_mg)
RetVal BVTNavData_GetOffsetNorth (BVTNavData obj, double *meters)
RetVal BVTNavData_SetOffsetNorth (BVTNavData obj, double meters)
RetVal BVTNavData_GetOffsetEast (BVTNavData obj, double *meters)
RetVal BVTNavData_SetOffsetEast (BVTNavData obj, double meters)
RetVal BVTNavData_GetOffsetIsFromLatLongFlag (BVTNavData obj, int *is_true)
RetVal BVTNavData_SetOffsetIsFromLatLongFlag (BVTNavData obj, int is_true)
char * BVTNavData_GetUserNavString (BVTNavData obj)
RetVal BVTNavData_SetUserNavString (BVTNavData obj, const char *string_in)
double BVTNavData_GetTimestamp (BVTNavData obj)
RetVal BVTNavData_SetTimestamp (BVTNavData obj, double sec)
Detailed Description
NavData contains various types of user-accessible navigation parameter, which can be saved to and retrieved from a sonar file on a per ping basis.
The NavData objects can be created and destroyed as needed. When the ping functions are called to get or put the data, the data is copied. This allows NavData objects to be pre-allocated and filled from various instrument sources. It also allows the data to be copied from one NavData object to the other. NOTE: NavData changes will only be saved to a sonar of type FILE.
Typedef Documentation
typedef void* BVTNavData
Opaque type for the BVTNavData object.
Function Documentation
BVTNavData BVTNavData_Create ()
Create a BVTNavData object.
Referenced by BVTSDK::NavData::NavData().
void BVTNavData_Destroy (BVTNavData obj)
Destroy a BVTNavData object.
Parameters:
obj Object pointer
Referenced by BVTSDK::NavData::~NavData().
RetVal BVTNavData_Clone (BVTNavData obj, const BVTNavData navdata_to_clone)
Clones the data from the passed NavData object to this object.
Both objects must have already been created.
Parameters:
obj Object pointer
navdata_to_clone existing NavData object to copy from
Referenced by BVTSDK::NavData::Clone().
RetVal BVTNavData_GetLatitude (BVTNavData obj, double * degrees)
Returns the latitude.
If no latitude was stored, returns BVT_NAV_NO_DATA.
Parameters:
obj Object pointer
degrees latitude in degrees
Referenced by BVTSDK::NavData::GetLatitude().
RetVal BVTNavData_SetLatitude (BVTNavData obj, double degrees)
Stores the latitude, as a signed floating point number of degrees.
Latitudes in the Western hemisphere are expressed as negative numbers.
Parameters:
obj Object pointer
degrees latitude in degrees
Referenced by BVTSDK::NavData::SetLatitude().
RetVal BVTNavData_GetLongitude (BVTNavData obj, double * degrees)
Returns the longitude.
If no longitude was stored, returns BVT_NAV_NO_DATA.
Parameters:
obj Object pointer
degrees longitude in degrees
Referenced by BVTSDK::NavData::GetLongitude().
RetVal BVTNavData_SetLongitude (BVTNavData obj, double degrees)
Stores the longitude, as a signed floating point number of degrees.
Longitudes in the Southern hemisphere are expressed as negative numbers.
Parameters:
obj Object pointer
degrees longitude in degrees
Referenced by BVTSDK::NavData::SetLongitude().
RetVal BVTNavData_GetHorizontalPrecisionError (BVTNavData obj, float * error_meters)
Returns the estimated horizontal error (see next function for details).
If none was stored, returns BVT_NAV_NO_DATA.
Parameters:
obj Object pointer
error_meters potential error distance, in meters
Referenced by BVTSDK::NavData::GetHorizontalPrecisionError().
RetVal BVTNavData_SetHorizontalPrecisionError (BVTNavData obj, float error_meters)
Stores the estimated possible horizontal error.
This is primarily (but not exclusively) intended for GPS systems, where there may be some doubt as to the quality of the position fix. HDOP is common, but not used here, as that is a unitless measure and varies between different manufacturers and models.
The idea is to use whatever calculations are appropriate for the local navigation system, and store a possible error value in meters. Some GPS units will attempt to give this directly. (for example, the HPE field in the PGRME sentence, supplied by some Garmin units.) In the case of large errors, or old data, it may be best to either not store a position, or not store new data. (also consider using the NavData time parameter to store the time of last fix, which can then be compared to the ping time when the data is read back to determine the age of the GPS reading.)
Parameters:
obj Object pointer
error_meters potential error distance, in meters
Referenced by BVTSDK::NavData::SetHorizontalPrecisionError().
RetVal BVTNavData_GetHeight (BVTNavData obj, float * meters_above_geoid)
Returns the height above mean sea level.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
obj Object pointer
meters_above_geoid height in floating point meters
Referenced by BVTSDK::NavData::GetHeight().
RetVal BVTNavData_SetHeight (BVTNavData obj, float meters_above_geoid)
Store the height above Mean Sea Level (usually the EGM96 geoid)).
Parameters:
obj Object pointer
meters_above_geoid altitude in floating point meters
Referenced by BVTSDK::NavData::SetHeight().
RetVal BVTNavData_GetVerticalPrecisionError (BVTNavData obj, float * error_meters)
Returns the estimated vertical error (see next function for details).
If none was stored, returns BVT_NAV_NO_DATA.
Parameters:
obj Object pointer
error_meters potential error distance, in meters
Referenced by BVTSDK::NavData::GetVerticalPrecisionError().
RetVal BVTNavData_SetVerticalPrecisionError (BVTNavData obj, float error_meters)
Stores the estimated possible vertical error (height) above Mean Sea Level (EGM96 geoid).
For other notes, see the functions or Horizontal Precision Error, above.
Parameters:
obj Object pointer
error_meters potential error distance, in meters
Referenced by BVTSDK::NavData::SetVerticalPrecisionError().
RetVal BVTNavData_GetDepth (BVTNavData obj, float * meters_below_surface)
Returns the depth.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
obj Object pointer
meters_below_surface depth in floating point meters
Referenced by BVTSDK::NavData::GetDepth().
RetVal BVTNavData_SetDepth (BVTNavData obj, float meters_below_surface)
Store the depth.
Parameters:
obj Object pointer
meters_below_surface depth in floating point meters
Referenced by BVTSDK::NavData::SetDepth().
RetVal BVTNavData_GetAltitude (BVTNavData obj, float * meters_above_bottom)
Returns the altitude.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
obj Object pointer
meters_above_bottom altitude in floating point meters
Referenced by BVTSDK::NavData::GetAltitude().
RetVal BVTNavData_SetAltitude (BVTNavData obj, float meters_above_bottom)
Store the altitude.
Parameters:
obj Object pointer
meters_above_bottom altitude in floating point meters
Referenced by BVTSDK::NavData::SetAltitude().
RetVal BVTNavData_GetHeading (BVTNavData obj, float * degrees_true)
Returns the heading relative to True North.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
obj Object pointer
degrees_true True heading, in degrees
Referenced by BVTSDK::NavData::GetHeading().
RetVal BVTNavData_SetHeading (BVTNavData obj, float degrees_true)
Store the heading relative to True North.
Parameters:
obj Object pointer
degrees_true True heading, in degrees
Referenced by BVTSDK::NavData::SetHeading().
RetVal BVTNavData_GetHeadingVelocity (BVTNavData obj, float * meters_per_second)
Returns the velocity along the heading.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
obj Object pointer
meters_per_second velocity, in meters per second
Referenced by BVTSDK::NavData::GetHeadingVelocity().
RetVal BVTNavData_SetHeadingVelocity (BVTNavData obj, float meters_per_second)
Store the velocity along the heading.
Parameters:
obj Object pointer
meters_per_second velocity, in meters per second
Referenced by BVTSDK::NavData::SetHeadingVelocity().
RetVal BVTNavData_GetCourseOverGround (BVTNavData obj, float * degrees_true)
Returns the course over ground (true).
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
obj Object pointer
degrees_true course over ground, true, in degrees
Referenced by BVTSDK::NavData::GetCourseOverGround().
RetVal BVTNavData_SetCourseOverGround (BVTNavData obj, float degrees_true)
Store the course over ground, true.
Parameters:
obj Object pointer
degrees_true course over ground, true, in degrees
Referenced by BVTSDK::NavData::SetCourseOverGround().
RetVal BVTNavData_GetSpeedOverGround (BVTNavData obj, float * meters_per_second)
Returns the speed over ground.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
obj Object pointer
meters_per_second speed over ground, in meters per second
Referenced by BVTSDK::NavData::GetSpeedOverGround().
RetVal BVTNavData_SetSpeedOverGround (BVTNavData obj, float meters_per_second)
Store the speed over ground.
Parameters:
obj Object pointer
meters_per_second speed over ground, in meters per second
Referenced by BVTSDK::NavData::SetSpeedOverGround().
RetVal BVTNavData_GetPitchAngle (BVTNavData obj, float * degrees_bow_up)
Get the pitch angle.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
obj Object pointer
degrees_bow_up pitch angle, in floating point degrees, bow up is positive
Referenced by BVTSDK::NavData::GetPitchAngle().
RetVal BVTNavData_SetPitchAngle (BVTNavData obj, float degrees_bow_up)
Store the pitch angle.
Parameters:
obj Object pointer
degrees_bow_up pitch angle, in floating point degrees, bow up is positive
Referenced by BVTSDK::NavData::SetPitchAngle().
RetVal BVTNavData_GetRollAngle (BVTNavData obj, float * degrees_port_up)
Get the roll angle.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
obj Object pointer
degrees_port_up roll angle, in floating point degrees, port side up is positive
Referenced by BVTSDK::NavData::GetRollAngle().
RetVal BVTNavData_SetRollAngle (BVTNavData obj, float degrees_port_up)
Store the roll angle.
Parameters:
obj Object pointer
degrees_port_up roll angle, in floating point degrees, port side up is positive
Referenced by BVTSDK::NavData::SetRollAngle().
RetVal BVTNavData_GetYawAngle (BVTNavData obj, float * degrees_bow_to_starboard)
Get the roll angle (but see notes with SetYawAngle()).
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
obj Object pointer
Referenced by BVTSDK::NavData::GetYawAngle().
RetVal BVTNavData_SetYawAngle (BVTNavData obj, float degrees_bow_to_starboard)
Store the yaw angle.
NOTE: This is NOT the same as the Heading field. Heading is for the normal navigation use of Heading, often from a compass. This field is intended to store raw data from other research instruments, in case you need another storage spot. To keep everyone using the fields the same way so that files can be interchanged, please use SetHeading for the normal heading, and SetYawAngle() only for special uses.
Parameters:
obj Object pointer
Referenced by BVTSDK::NavData::SetYawAngle().
RetVal BVTNavData_GetPitchRate (BVTNavData obj, float * degrees_per_second)
Returns the rate of pitch change.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
obj Object pointer
degrees_per_second rate of pitch change in degrees per second
Referenced by BVTSDK::NavData::GetPitchRate().
RetVal BVTNavData_SetPitchRate (BVTNavData obj, float degrees_per_second)
Store the the rate of pitch change.
Parameters:
obj Object pointer
degrees_per_second rate of pitch change in degrees per second
Referenced by BVTSDK::NavData::SetPitchRate().
RetVal BVTNavData_GetRollRate (BVTNavData obj, float * degrees_per_second)
Returns the rate of roll change.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
obj Object pointer
degrees_per_second rate of roll change in degrees per second
Referenced by BVTSDK::NavData::GetRollRate().
RetVal BVTNavData_SetRollRate (BVTNavData obj, float degrees_per_second)
Store the the rate of change in roll.
Parameters:
obj Object pointer
degrees_per_second rate of roll change in floating point degrees per second
Referenced by BVTSDK::NavData::SetRollRate().
RetVal BVTNavData_GetYawRate (BVTNavData obj, float * degrees_per_second)
Returns the rate of change in yaw (heading).
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
obj Object pointer
degrees_per_second rate of yaw change in floating point degrees per second
Referenced by BVTSDK::NavData::GetYawRate().
RetVal BVTNavData_SetYawRate (BVTNavData obj, float degrees_per_second)
Store the rate of change in yaw (heading).
Parameters:
obj Object pointer
degrees_per_second rate of yaw change in floating point degrees per second
Referenced by BVTSDK::NavData::SetYawRate().
RetVal BVTNavData_GetAccelerationX (BVTNavData obj, float * accel_mg)
Gets the stored acceleration along the X axis.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
obj Object pointer
accel_mg acceleration along X axis, in milli-g
Referenced by BVTSDK::NavData::GetAccelerationX().
RetVal BVTNavData_SetAccelerationX (BVTNavData obj, float accel_mg)
Sets the stored acceleration along the X axis.
Intended to store raw values of accelerometers.
Parameters:
obj Object pointer
accel_mg acceleration along X axis, in milli-g
Referenced by BVTSDK::NavData::SetAccelerationX().
RetVal BVTNavData_GetAccelerationY (BVTNavData obj, float * accel_mg)
Gets the stored acceleration along the Y axis.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
obj Object pointer
accel_mg acceleration along Y axis, in milli-g
Referenced by BVTSDK::NavData::GetAccelerationY().
RetVal BVTNavData_SetAccelerationY (BVTNavData obj, float accel_mg)
Sets the stored acceleration along the Y axis.
Intended to store raw values of accelerometers.
Parameters:
obj Object pointer
accel_mg acceleration along Y axis, in milli-g
Referenced by BVTSDK::NavData::SetAccelerationY().
RetVal BVTNavData_GetAccelerationZ (BVTNavData obj, float * accel_mg)
Gets the stored acceleration along the Z axis.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
obj Object pointer
accel_mg acceleration along Z axis, in milli-g
Referenced by BVTSDK::NavData::GetAccelerationZ().
RetVal BVTNavData_SetAccelerationZ (BVTNavData obj, float accel_mg)
Sets the stored acceleration along the Z axis.
Intended to store raw values of accelerometers.
Parameters:
obj Object pointer
accel_mg acceleration along Z axis, in milli-g
Referenced by BVTSDK::NavData::SetAccelerationZ().
RetVal BVTNavData_GetOffsetNorth (BVTNavData obj, double * meters)
Returns the offset, to the north, from a user-defined fixed point.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
obj Object pointer
meters offset to the north, in floating point meters
Referenced by BVTSDK::NavData::GetOffsetNorth().
RetVal BVTNavData_SetOffsetNorth (BVTNavData obj, double meters)
Store the offset from a user-defined fixed point.
Parameters:
obj Object pointer
meters offset to the north, in floating point meters
Referenced by BVTSDK::NavData::SetOffsetNorth().
RetVal BVTNavData_GetOffsetEast (BVTNavData obj, double * meters)
Returns the offset, to the east, from a user-defined fixed point.
If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
obj Object pointer
meters offset to the east, in floating point meters
Referenced by BVTSDK::NavData::GetOffsetEast().
RetVal BVTNavData_SetOffsetEast (BVTNavData obj, double meters)
Store the offset from a user-defined fixed point.
Parameters:
obj Object pointer
meters offset to the east, in floating point meters
Referenced by BVTSDK::NavData::SetOffsetEast().
RetVal BVTNavData_GetOffsetIsFromLatLongFlag (BVTNavData obj, int * is_true)
Gets a flag value which indicates if the East and North offset values are from the stored Latitude and Longitude.
(see more below...) If no value was stored for this ping, returns BVT_NAV_NO_DATA.
Parameters:
obj Object pointer
is_true either 1 or 0, to indicate true or false, respectively
Referenced by BVTSDK::NavData::GetOffsetIsFromLatLongFlag().
RetVal BVTNavData_SetOffsetIsFromLatLongFlag (BVTNavData obj, int is_true)
Sets a flag to indicate if the East and North offset values are from the stored Latitude and Longitude.
If so, then software reading the file will know to adjust appropriately. If from some special location, perhaps the UserNavString could be used to indicate the reference point? If nothing is stored, then the value is assumed to be false.
Parameters:
obj Object pointer
is_true either 1 or 0, to indicate true or false, respectively
Referenced by BVTSDK::NavData::SetOffsetIsFromLatLongFlag().
char* BVTNavData_GetUserNavString (BVTNavData obj)
Returns the stored user string, in null-terminated form.
If no string was stored, returns a null string.
Parameters:
obj Object pointer
Referenced by BVTSDK::NavData::GetUserNavString().
RetVal BVTNavData_SetUserNavString (BVTNavData obj, const char * string_in)
Stores a user-defined string related to navigation.
It is highly recommended to store some identifier such that the data is recognizable as you own.
Examples of possible uses might be to store locations based on coordinate systems other than GPS, indicating information about the use of the north and east offset parameters, additional fields from a GPS receiver, or any other information which might change dynamically.
Parameters:
obj Object pointer
string_in string to be stored, null terminated, max length 80 chars
Referenced by BVTSDK::NavData::SetUserNavString().
double BVTNavData_GetTimestamp (BVTNavData obj)
Return the ping's timestamp in seconds since 00:00:00 UTC, January 1, 1970 Pings are timestamped using a standard UNIX time stamp.
This is a similar value to that returned by the time() C standard library function. In fact, the only difference is the addition of fractional seconds.
Parameters:
obj Object pointer
Referenced by BVTSDK::NavData::GetTimestamp().
RetVal BVTNavData_SetTimestamp (BVTNavData obj, double sec)
Set the NavData's internal time stamp.
See GetTimestamp() for more information.
Parameters:
obj Object pointer
sec Timestamp in seconds since 00:00:00 UTC, January 1, 1970
Referenced by BVTSDK::NavData::SetTimestamp().