ProViewer SDK: BVTColorImage Object
BVTColorImage Object
Store a color image.
Typedefs
typedef void * BVTColorImage
Functions
void BVTColorImage_Destroy (BVTColorImage obj)
int BVTColorImage_GetHeight (BVTColorImage obj)
int BVTColorImage_GetWidth (BVTColorImage obj)
double BVTColorImage_GetRangeResolution (BVTColorImage obj)
int BVTColorImage_GetOriginRow (BVTColorImage obj)
int BVTColorImage_GetOriginCol (BVTColorImage obj)
double BVTColorImage_GetPixelRange (BVTColorImage obj, int row, int col)
double BVTColorImage_GetPixelRelativeBearing (BVTColorImage obj, int row, int col)
double BVTColorImage_GetFOVMinAngle (BVTColorImage obj)
double BVTColorImage_GetFOVMaxAngle (BVTColorImage obj)
unsigned int BVTColorImage_GetPixel (BVTColorImage obj, int row, int col)
unsigned int * BVTColorImage_GetRow (BVTColorImage obj, int row)
unsigned int * BVTColorImage_GetBits (BVTColorImage obj)
RetVal BVTColorImage_CopyBits (BVTColorImage obj, unsigned int *data, unsigned int len)
RetVal BVTColorImage_SavePPM (BVTColorImage obj, const char *file_name)
Detailed Description
Store a color image.
The API is nearly identical to MagImage. The main difference is the pixel datatype. In ColorImage, each pixel is a single unsigned int.
Byte 0: Red Value
Byte 1: Green Value
Byte 2: Blue Value
Byte 3: Alpha Value
Typedef Documentation
typedef void* BVTColorImage
Opaque type for the BVTColorImage object.
Function Documentation
void BVTColorImage_Destroy (BVTColorImage obj)
Destroy a BVTColorImage object.
Parameters:
obj Object pointer
Referenced by BVTSDK::ColorImage::~ColorImage().
int BVTColorImage_GetHeight (BVTColorImage obj)
Return the height (in pixels) of this image.
Parameters:
obj Object pointer
Referenced by BVTSDK::ColorImage::GetHeight().
int BVTColorImage_GetWidth (BVTColorImage obj)
Return the width (in pixels) of this image.
Parameters:
obj Object pointer
Referenced by BVTSDK::ColorImage::GetWidth().
double BVTColorImage_GetRangeResolution (BVTColorImage obj)
Return the range resolution of this image.
The resolution is returned in meters per pixel
Parameters:
obj Object pointer
Referenced by BVTSDK::ColorImage::GetRangeResolution().
int BVTColorImage_GetOriginRow (BVTColorImage obj)
Retrieve the image row of the origin.
In most cases the origin will be outside of the image boundaries. The origin is the 'location' (in pixels) of the sonar head in image plane
Parameters:
obj Object pointer
Referenced by BVTSDK::ColorImage::GetOriginRow().
int BVTColorImage_GetOriginCol (BVTColorImage obj)
Retrieve the image column of the origin.
In most cases the origin will be outside of the image boundaries. The origin is the 'location' (in pixels) of the sonar head in image plane
Parameters:
obj Object pointer
Referenced by BVTSDK::ColorImage::GetOriginCol().
double BVTColorImage_GetPixelRange (BVTColorImage obj, int row, int col)
Retrieve the range (from the sonar head) of the specified pixel.
Parameters:
obj Object pointer
row Origin row
col Origin col
Referenced by BVTSDK::ColorImage::GetPixelRange().
double BVTColorImage_GetPixelRelativeBearing (BVTColorImage obj, int row, int col)
Retrieve the bearing relative to the sonar head of the specified pixel.
Parameters:
obj Object pointer
row Origin row
col Origin col
Referenced by BVTSDK::ColorImage::GetPixelRelativeBearing().
double BVTColorImage_GetFOVMinAngle (BVTColorImage obj)
Return the minimum angle for the sonar's imaging field of view.
The angle is returned in degrees.
Parameters:
obj Object pointer
Referenced by BVTSDK::ColorImage::GetFOVMinAngle().
double BVTColorImage_GetFOVMaxAngle (BVTColorImage obj)
Return the maximum angle for the sonar's imaging field of view.
The angle is returned in degrees.
Parameters:
obj Object pointer
Referenced by BVTSDK::ColorImage::GetFOVMaxAngle().
unsigned int BVTColorImage_GetPixel (BVTColorImage obj, int row, int col)
Return the value of the pixel at (row, col).
Parameters:
obj Object pointer
row Requested row
col Requested col
Referenced by BVTSDK::ColorImage::GetPixel().
unsigned int* BVTColorImage_GetRow (BVTColorImage obj, int row)
Return a pointer to a row of pixels.
Parameters:
obj Object pointer
row Requested row
Referenced by BVTSDK::ColorImage::GetRow().
unsigned int* BVTColorImage_GetBits (BVTColorImage obj)
Return a pointer to the entire image.
The image or organized in Row-Major order (just like C/C++).
Parameters:
obj Object pointer
Referenced by BVTSDK::ColorImage::GetBits().
RetVal BVTColorImage_CopyBits (BVTColorImage obj, unsigned int * data, unsigned int len)
Copy the raw image data to the user specified buffer.
See GetBits for more info.
Parameters:
obj Object pointer
data Pointer to a valid buffer
len The size of the buffer pointed to by data in pixels NOT bytes.
Referenced by BVTSDK::ColorImage::CopyBits().
RetVal BVTColorImage_SavePPM (BVTColorImage obj, const char * file_name)
Save the image in PPM (PortablePixMap) format.
Parameters:
obj Object pointer
file_name File name to save to
Referenced by BVTSDK::ColorImage::SavePPM().