ProViewer SDK: BVTRangeData Object
BVTRangeData Object
** EXPERIMENTAL ** This functionality is still under development! *** RangeData is a set of ranges from the sonar head, at various angles from the sonar head.
Defines
#define BVTRANGEDATA_MAX_RANGE (int)(999)
Typedefs
typedef void * BVTRangeData
Functions
int BVTRangeData_GetCount (BVTRangeData obj)
double BVTRangeData_GetRangeResolution (BVTRangeData obj)
double BVTRangeData_GetBearingResolution (BVTRangeData obj)
float BVTRangeData_GetFOVMinAngle (BVTRangeData obj)
float BVTRangeData_GetFOVMaxAngle (BVTRangeData obj)
RetVal BVTRangeData_CopyRangeValues (BVTRangeData obj, float *ranges, int number_of_ranges)
float BVTRangeData_GetRangeValue (BVTRangeData obj, int index)
float BVTRangeData_GetBearingValue (BVTRangeData obj, int index)
int BVTRangeData_GetColorImagePixelX (BVTRangeData obj, int rangeDataIndex, const BVTColorImage image)
int BVTRangeData_GetColorImagePixelY (BVTRangeData obj, int rangeDataIndex, const BVTColorImage image)
Detailed Description
** EXPERIMENTAL ** This functionality is still under development! *** RangeData is a set of ranges from the sonar head, at various angles from the sonar head.
For each angle, the range, bearing and intensity of the return beam at that range is stored. NOTE: RangeData only applies to specialized BlueView sonars, and has no use for our standard imaging sonars.
Define Documentation
#define BVTRANGEDATA_MAX_RANGE (int)(999)
Values greater than this indicate no range could be measured.
Typedef Documentation
typedef void* BVTRangeData
Opaque type for the BVTRangeData object.
Function Documentation
int BVTRangeData_GetCount (BVTRangeData obj)
Returns the number of range values stored for this ping.
Parameters:
obj Object pointer
Referenced by BVTSDK::RangeData::GetCount().
double BVTRangeData_GetRangeResolution (BVTRangeData obj)
Returns the resolution of the range values, in meters.
Parameters:
obj Object pointer
Referenced by BVTSDK::RangeData::GetRangeResolution().
double BVTRangeData_GetBearingResolution (BVTRangeData obj)
Returns the resolution of the bearing stored with each range value.
This is the difference in bearing between each range value in the array.
Parameters:
obj Object pointer
Referenced by BVTSDK::RangeData::GetBearingResolution().
float BVTRangeData_GetFOVMinAngle (BVTRangeData obj)
Return the minimum angle for the sonar's imaging field of view.
In other words, this is the angle of the first range value, as all angles are "left referenced."The angle is returned in degrees. Note that this may not represent the actual physical field of view of a particular sonar, but does represent the field of view of the data being returned. Some outside values may have range values indicating they are out of range.
Parameters:
obj Object pointer
Referenced by BVTSDK::RangeData::GetFOVMinAngle().
float BVTRangeData_GetFOVMaxAngle (BVTRangeData obj)
Return the maximum angle for the sonar's imaging field of view.
In other words, this is the angle of the last range value, as all angles are "left referenced."The angle is returned in degrees. Note that this may not represent the actual physical field of view of a particular sonar, but does represent the field of view of the data being returned. Some outside values may have range values indicating they are out of range.
Parameters:
obj Object pointer
Referenced by BVTSDK::RangeData::GetFOVMaxAngle().
RetVal BVTRangeData_CopyRangeValues (BVTRangeData obj, float * ranges, int number_of_ranges)
Copies the range values into the user specified buffer.
The buffer must hold the entire number of ranges (See GetCount() above), or an error is returned.
Parameters:
obj Object pointer
ranges Pointer to a valid buffer of type float.
number_of_ranges Number of values the buffer can hold.
Referenced by BVTSDK::RangeData::CopyRangeValues().
float BVTRangeData_GetRangeValue (BVTRangeData obj, int index)
Returns the range from the sonar head, in meters, at a particular index into the array.
NOTE: Check all returned values for validity. If range > BVTRANGEDATA_MAX_RANGE then the range could not be determined within the capabilities of the sonar. Meaning that the closest object at that bearing was either out of view of the sonar, or the threshold was set too high to be detected.
Parameters:
obj Object pointer
index index into the array of RangeData values
Referenced by BVTSDK::RangeData::GetRangeValue().
float BVTRangeData_GetBearingValue (BVTRangeData obj, int index)
Returns the bearing from the center of the sonar head, in degrees (+/-), at a particular index into the array.
Parameters:
obj Object pointer
index index into the array of RangeData values
Referenced by BVTSDK::RangeData::GetBearingValue().
int BVTRangeData_GetColorImagePixelX (BVTRangeData obj, int rangeDataIndex, const BVTColorImage image)
Returns the X coordinate for the pixel in the passed ColorImage, which maps to the range and bearing at the index passed.
This allows placing of the range data on a colorimage, easing analysis of the algorithm used for thresholding.
Parameters:
obj Object pointer
image ColorImage object where the pixel coordinate is needed
Referenced by BVTSDK::RangeData::GetColorImagePixelX().
int BVTRangeData_GetColorImagePixelY (BVTRangeData obj, int rangeDataIndex, const BVTColorImage image)
Returns the Y coordinate for the pixel in the passed ColorImage which maps to the range and bearing at the index passed.
(see similar function, above, for more details)
Parameters:
obj Object pointer
image ColorImage object where the pixel coordinate is needed
Referenced by BVTSDK::RangeData::GetColorImagePixelY().