ProViewer SDK: BVTColorMapper Object
BVTColorMapper Object
Provide support for applying a colormap to a MagImage, thus generating a ColorImage.
Typedefs
typedef void * BVTColorMapper
Functions
BVTColorMapper BVTColorMapper_Create ()
void BVTColorMapper_Destroy (BVTColorMapper obj)
RetVal BVTColorMapper_Load (BVTColorMapper obj, const char *file)
RetVal BVTColorMapper_SetGamma (BVTColorMapper obj, float gamma)
float BVTColorMapper_GetGamma (BVTColorMapper obj)
RetVal BVTColorMapper_SetThresholds (BVTColorMapper obj, int top, int bottom)
int BVTColorMapper_GetTopThreshold (BVTColorMapper obj)
int BVTColorMapper_GetBottomThreshold (BVTColorMapper obj)
int BVTColorMapper_GetAutoMode (BVTColorMapper obj)
RetVal BVTColorMapper_SetAutoMode (BVTColorMapper obj, int mode)
RetVal BVTColorMapper_MapImage (BVTColorMapper obj, const BVTMagImage input, BVTColorImage *output)
Detailed Description
Provide support for applying a colormap to a MagImage, thus generating a ColorImage.
Typedef Documentation
typedef void* BVTColorMapper
Opaque type for the BVTColorMapper object.
Function Documentation
BVTColorMapper BVTColorMapper_Create ()
Create a BVTColorMapper object.
Referenced by BVTSDK::ColorMapper::ColorMapper().
void BVTColorMapper_Destroy (BVTColorMapper obj)
Destroy a BVTColorMapper object.
Parameters:
obj Object pointer
Referenced by BVTSDK::ColorMapper::~ColorMapper().
RetVal BVTColorMapper_Load (BVTColorMapper obj, const char * file)
Load a color map file.
Parameters:
obj Object pointer
file Colormap file name
Referenced by BVTSDK::ColorMapper::Load().
RetVal BVTColorMapper_SetGamma (BVTColorMapper obj, float gamma)
Set the gamma used when colormapping.
Parameters:
obj Object pointer
gamma Gamma value
Referenced by BVTSDK::ColorMapper::SetGamma().
float BVTColorMapper_GetGamma (BVTColorMapper obj)
Return the current gamma.
Parameters:
obj Object pointer
Referenced by BVTSDK::ColorMapper::GetGamma().
RetVal BVTColorMapper_SetThresholds (BVTColorMapper obj, int top, int bottom)
Set the intensity values to be mapped to the top and bottom of the colormap.
If auto intensity is enabled, this function returns an error.
Parameters:
obj Object pointer
top Top colormap threshold (aka intensity)
bottom Bottom colormap threshold
Referenced by BVTSDK::ColorMapper::SetThresholds().
int BVTColorMapper_GetTopThreshold (BVTColorMapper obj)
Return the upper threshold for the colormap.
The top threshold is also known as 'intensity'. Lowering the top threshold will make a brighter image.
Parameters:
obj Object pointer
Referenced by BVTSDK::ColorMapper::GetTopThreshold().
int BVTColorMapper_GetBottomThreshold (BVTColorMapper obj)
Return the lower threshold for the colormap.
Parameters:
obj Object pointer
Referenced by BVTSDK::ColorMapper::GetBottomThreshold().
int BVTColorMapper_GetAutoMode (BVTColorMapper obj)
Return a number greater than 0 if auto-threshold is enabled, 0 if it's not.
Parameters:
obj Object pointer
Referenced by BVTSDK::ColorMapper::GetAutoMode().
RetVal BVTColorMapper_SetAutoMode (BVTColorMapper obj, int mode)
Enable or disable an internal auto-threshold algorithm.
Parameters:
obj Object pointer
mode > 0 if auto-threshold should be enabled. 0 otherwise.
Referenced by BVTSDK::ColorMapper::SetAutoMode().
RetVal BVTColorMapper_MapImage (BVTColorMapper obj, const BVTMagImage input, BVTColorImage * output)
Colormap an image.
Parameters:
obj Object pointer
input Input magnitude image
output Output color image
Referenced by BVTSDK::ColorMapper::MapImage().