ProViewer SDK: BVTMagImage Object
BVTMagImage Object
MagImage is short for MagnitudeImage.
Typedefs
typedef void * BVTMagImage
Functions
void BVTMagImage_Destroy (BVTMagImage obj)
int BVTMagImage_GetHeight (BVTMagImage obj)
int BVTMagImage_GetWidth (BVTMagImage obj)
double BVTMagImage_GetRangeResolution (BVTMagImage obj)
double BVTMagImage_GetBearingResolution (BVTMagImage obj)
int BVTMagImage_GetOriginRow (BVTMagImage obj)
int BVTMagImage_GetOriginCol (BVTMagImage obj)
double BVTMagImage_GetPixelRange (BVTMagImage obj, int row, int col)
double BVTMagImage_GetPixelRelativeBearing (BVTMagImage obj, int row, int col)
double BVTMagImage_GetFOVMinAngle (BVTMagImage obj)
double BVTMagImage_GetFOVMaxAngle (BVTMagImage obj)
unsigned short BVTMagImage_GetPixel (BVTMagImage obj, int row, int col)
unsigned short * BVTMagImage_GetRow (BVTMagImage obj, int row)
unsigned short * BVTMagImage_GetBits (BVTMagImage obj)
RetVal BVTMagImage_CopyBits (BVTMagImage obj, unsigned short *data, unsigned int len)
RetVal BVTMagImage_SavePGM (BVTMagImage obj, const char *file_name)
Detailed Description
MagImage is short for MagnitudeImage.
It provides access to a 2d image where each pixel is intensity of the return from a particular point on a plane emanating from the head. It can be thought of as a 16bit grey-scale image.
Typedef Documentation
typedef void* BVTMagImage
Opaque type for the BVTMagImage object.
Function Documentation
void BVTMagImage_Destroy (BVTMagImage obj)
Destroy a BVTMagImage object.
Parameters:
obj Object pointer
Referenced by BVTSDK::MagImage::~MagImage().
int BVTMagImage_GetHeight (BVTMagImage obj)
Return the height (in pixels) of this image.
Parameters:
obj Object pointer
Referenced by BVTSDK::MagImage::GetHeight().
int BVTMagImage_GetWidth (BVTMagImage obj)
Return the width (in pixels) of this image.
Parameters:
obj Object pointer
Referenced by BVTSDK::MagImage::GetWidth().
double BVTMagImage_GetRangeResolution (BVTMagImage obj)
Return the range resolution of this image.
The resolution is returned in meters per pixel.
Parameters:
obj Object pointer
Referenced by BVTSDK::MagImage::GetRangeResolution().
double BVTMagImage_GetBearingResolution (BVTMagImage obj)
Only valid for R-Theta images.
Returns the bearing resolution, in degrees per column.
Parameters:
obj Object pointer
Referenced by BVTSDK::MagImage::GetBearingResolution().
int BVTMagImage_GetOriginRow (BVTMagImage obj)
Retrieve the image row of the origin.
In most cases the origin will be outside of the image boundaries. The origin is the 'location' (in pixels) of the sonar head in image plane
Parameters:
obj Object pointer
Referenced by BVTSDK::MagImage::GetOriginRow().
int BVTMagImage_GetOriginCol (BVTMagImage obj)
Retrieve the image column of the origin.
In most cases the origin will be outside of the image boundaries. The origin is the 'location' (in pixels) of the sonar head in image plane
Parameters:
obj Object pointer
Referenced by BVTSDK::MagImage::GetOriginCol().
double BVTMagImage_GetPixelRange (BVTMagImage obj, int row, int col)
Retrieve the range (from the sonar head) of the specified pixel.
Parameters:
obj Object pointer
row Origin row
col Origin col
Referenced by BVTSDK::MagImage::GetPixelRange().
double BVTMagImage_GetPixelRelativeBearing (BVTMagImage obj, int row, int col)
Retrieve the bearing relative to the sonar head of the specified pixel.
Parameters:
obj Object pointer
row Origin row
col Origin col
Referenced by BVTSDK::MagImage::GetPixelRelativeBearing().
double BVTMagImage_GetFOVMinAngle (BVTMagImage obj)
Return the minimum angle for the sonar's imaging field of view.
The angle is returned in degrees.
Parameters:
obj Object pointer
Referenced by BVTSDK::MagImage::GetFOVMinAngle().
double BVTMagImage_GetFOVMaxAngle (BVTMagImage obj)
Return the maximum angle for the sonar's imaging field of view.
The angle is returned in degrees.
Parameters:
obj Object pointer
Referenced by BVTSDK::MagImage::GetFOVMaxAngle().
unsigned short BVTMagImage_GetPixel (BVTMagImage obj, int row, int col)
Return the value of the pixel at (row, col).
Parameters:
obj Object pointer
row Requested row
col Requested col
Referenced by BVTSDK::MagImage::GetPixel().
unsigned short* BVTMagImage_GetRow (BVTMagImage obj, int row)
Return a pointer to a row of pixels.
Parameters:
obj Object pointer
row Requested row
Referenced by BVTSDK::MagImage::GetRow().
unsigned short* BVTMagImage_GetBits (BVTMagImage obj)
Return a pointer to the entire image.
The image or organized in Row-Major order (just like C/C++).
Parameters:
obj Object pointer
Referenced by BVTSDK::MagImage::GetBits().
RetVal BVTMagImage_CopyBits (BVTMagImage obj, unsigned short * data, unsigned int len)
Copy the raw image data to the user specified buffer.
See GetBits for more info.
Parameters:
obj Object pointer
data Pointer to a valid buffer
len The size of the buffer pointed to by data in pixels NOT bytes.
Referenced by BVTSDK::MagImage::CopyBits().
RetVal BVTMagImage_SavePGM (BVTMagImage obj, const char * file_name)
Save the image in PGM (PortableGreyMap) format.
Note that few programs actually support loading a 16bit PGM.
Parameters:
obj Object pointer
file_name File name to save to
Referenced by BVTSDK::MagImage::SavePGM().