ProViewer SDK: BVTSonar Object
BVTSonar Object
The Sonar object is the top level object in the SDK.
Typedefs
typedef void * BVTSonar
Functions
BVTSonar BVTSonar_Create ()
void BVTSonar_Destroy (BVTSonar obj)
RetVal BVTSonar_Open (BVTSonar obj, const char *type, const char *type_params)
RetVal BVTSonar_CreateFile (BVTSonar obj, const char *file_name, const BVTSonar src, const char *create_params)
int BVTSonar_GetFileSize (BVTSonar obj)
RetVal BVTSonar_GetHead (BVTSonar obj, int head_num, BVTHead *head)
int BVTSonar_GetHeadCount (BVTSonar obj)
RetVal BVTSonar_GetSonarTypeAsString (BVTSonar obj, char *buffer, int buffer_size)
RetVal BVTSonar_GetSonarName (BVTSonar obj, char *buffer, int buffer_size)
float BVTSonar_GetTemperature (BVTSonar obj)
Detailed Description
The Sonar object is the top level object in the SDK.
A sonar object embodies communication with a single physical sonar unit, or file. Each sonar contains several heads, which is where most of the functionality is implemented. Sonar also provides a function to create new data files using BlueView's .son format.
Typedef Documentation
typedef void* BVTSonar
Opaque type for the BVTSonar object.
Function Documentation
BVTSonar BVTSonar_Create ()
Create a BVTSonar object.
Referenced by BVTSDK::Sonar::Sonar().
void BVTSonar_Destroy (BVTSonar obj)
Destroy a BVTSonar object.
Parameters:
obj Object pointer
Referenced by BVTSDK::Sonar::~Sonar().
RetVal BVTSonar_Open (BVTSonar obj, const char * type, const char * type_params)
Open the sonar type 'type' using the specified parameters.
Allowed types (and parameters):
FILE
[filename] - Required
NET
[host] - Connect to the specified host.
Parameters:
obj Object pointer
type The type of sonar to open
type_params Various type-specific parameters
Referenced by BVTSDK::Sonar::Open().
RetVal BVTSonar_CreateFile (BVTSonar obj, const char * file_name, const BVTSonar src, const char * create_params)
Create a new data file.
Files are always created by 'cloning' another Sonar object. This ensures that the file receives all the needed setup/configuration data needed to process images.
Parameters:
obj Object pointer
file_name The filename of the file to be created
src The Sonar object to clone when creating the file
create_params Parameters for (reserved for future use)
Referenced by BVTSDK::Sonar::CreateFile().
int BVTSonar_GetFileSize (BVTSonar obj)
Gets the size of a file created with CreateFile().
Only works with file type sonars. A networked sonar will return 0, as will a file type sonar if there is no open file associated with it. The return value must be multiplied by 1000 to get the actual file size in bytes.
Parameters:
obj Object pointer
Referenced by BVTSDK::Sonar::GetFileSize().
RetVal BVTSonar_GetHead (BVTSonar obj, int head_num, BVTHead * head)
Retrieve a Head object from the sonar.
Parameters:
obj Object pointer
head_num The head number to return
head The returned Head object
Referenced by BVTSDK::Sonar::GetHead().
int BVTSonar_GetHeadCount (BVTSonar obj)
Return the number of heads on this sonar.
Parameters:
obj Object pointer
Referenced by BVTSDK::Sonar::GetHeadCount().
RetVal BVTSonar_GetSonarTypeAsString (BVTSonar obj, char * buffer, int buffer_size)
Retrieves a copy of a short string with the model of the sonar.
At the time of this writing, 20 characters would easily hold all of the sonar model names.
Parameters:
obj Object pointer
buffer buffer to hold the null-terminated string to be passed back
buffer_size total number of characters the passed buffer can hold
Referenced by BVTSDK::Sonar::GetSonarTypeAsString().
RetVal BVTSonar_GetSonarName (BVTSonar obj, char * buffer, int buffer_size)
Retrieves a copy of the name of the sonar.
The name is set only via the ProViewer application (at least at this time), or at the factory, and is separate from any BlueView model designations.
The length of the name could be considerably longer than the sonar type, and there is no actual limit, though 80 characters would seem to be more than enough.
Parameters:
obj Object pointer
buffer buffer to hold the null-terminated string to be passed back
buffer_size total number of characters the passed buffer can hold
Referenced by BVTSDK::Sonar::GetSonarName().
float BVTSonar_GetTemperature (BVTSonar obj)
Return the sonar's internal temperature in degrees Celsius If the sonar doesn't have a temp sensor this function returns absolute zero (-273.15).
Parameters:
obj Object pointer
Referenced by BVTSDK::Sonar::GetTemperature().