ProViewer SDK: BVTHead Object
BVTHead Object
A head consists of a group of co-planar transducers which are operated simultaneously to produce (ultimately) a single 2d image.
Defines
#define BVTHEAD_FLUID_SALTWATER (int)(0)
#define BVTHEAD_FLUID_FRESHWATER (int)(1)
#define BVTHEAD_FLUID_OTHER (int)(2)
#define BVTHEAD_RES_OFF (int)(0)
#define BVTHEAD_RES_LOW (int)(1)
#define BVTHEAD_RES_MED (int)(2)
#define BVTHEAD_RES_HIGH (int)(3)
#define BVTHEAD_RES_AUTO (int)(4)
#define BVTHEAD_IMAGE_XY (int)(0)
#define BVTHEAD_IMAGE_RTHETA (int)(1)
Typedefs
typedef void * BVTHead
Functions
RetVal BVTHead_GetHeadName (BVTHead obj, char *buffer, int buffer_size)
RetVal BVTHead_SetRange (BVTHead obj, float start, float stop)
float BVTHead_GetStartRange (BVTHead obj)
float BVTHead_GetStopRange (BVTHead obj)
float BVTHead_GetMinimumRange (BVTHead obj)
float BVTHead_GetMaximumRange (BVTHead obj)
int BVTHead_GetFluidType (BVTHead obj)
RetVal BVTHead_SetFluidType (BVTHead obj, int fluid)
int BVTHead_GetSoundSpeed (BVTHead obj)
RetVal BVTHead_SetSoundSpeed (BVTHead obj, int speed)
float BVTHead_GetGainAdjustment (BVTHead obj)
RetVal BVTHead_SetGainAdjustment (BVTHead obj, float gain)
float BVTHead_GetTVGSlope (BVTHead obj)
RetVal BVTHead_SetTVGSlope (BVTHead obj, float tvg)
int BVTHead_GetCenterFreq (BVTHead obj)
int BVTHead_GetPingCount (BVTHead obj)
RetVal BVTHead_GetPing (BVTHead obj, int ping_num, BVTPing *ping)
RetVal BVTHead_PutPing (BVTHead obj, const BVTPing ping)
RetVal BVTHead_SetImageRes (BVTHead obj, int res)
RetVal BVTHead_SetRangeResolution (BVTHead obj, float resolution_in_meters)
RetVal BVTHead_SetImageReqSize (BVTHead obj, int height, int width)
RetVal BVTHead_SetRemoteBeamForming (BVTHead obj, int enable)
RetVal BVTHead_SetRawDataSending (BVTHead obj, int enable)
RetVal BVTHead_SetRemoteImageForming (BVTHead obj, int enable)
RetVal BVTHead_SetImageType (BVTHead obj, int type)
int BVTHead_GetImageFilterFlags (BVTHead obj)
RetVal BVTHead_SetImageFilterFlags (BVTHead obj, int flags)
RetVal BVTHead_SetRangeDataThreshold (BVTHead obj, unsigned short noise_threshold)
RetVal BVTHead_SetTxEnable (BVTHead obj, int enableTx)
RetVal BVTHead_GetMountingOrientation (BVTHead obj, double *X_axis_degrees, double *Y_axis_degrees, double *Z_axis_degrees)
RetVal BVTHead_SetMountingOrientation (BVTHead obj, double X_axis_degrees, double Y_axis_degrees, double Z_axis_degrees)
Detailed Description
A head consists of a group of co-planar transducers which are operated simultaneously to produce (ultimately) a single 2d image.
The Head object provides functions to change the range window as well as produce pings.
Define Documentation
#define BVTHEAD_FLUID_SALTWATER (int)(0)
#define BVTHEAD_FLUID_FRESHWATER (int)(1)
#define BVTHEAD_FLUID_OTHER (int)(2)
#define BVTHEAD_RES_OFF (int)(0)
Turn off image processing.
#define BVTHEAD_RES_LOW (int)(1)
Process at low resolution.
#define BVTHEAD_RES_MED (int)(2)
Process at med resolution.
#define BVTHEAD_RES_HIGH (int)(3)
Process at high resolution.
#define BVTHEAD_RES_AUTO (int)(4)
Select a good res for the current range automatically.
#define BVTHEAD_IMAGE_XY (int)(0)
Output a cartesian image.
#define BVTHEAD_IMAGE_RTHETA (int)(1)
Output a Range/Theta image.
Typedef Documentation
typedef void* BVTHead
Opaque type for the BVTHead object.
Function Documentation
RetVal BVTHead_GetHeadName (BVTHead obj, char * buffer, int buffer_size)
Retrieves a copy of a the name of the head.
The head name is currently set only at the factory, and is simply "Head" on many sonars. Only special order sonars with multiple heads are likely to have a different name.
The length of the name has no actual limit, though 80 characters would seem to be more than enough.
Parameters:
obj Object pointer
buffer buffer to hold the null-terminated string to be passed back
buffer_size total number of characters the passed buffer can hold
Referenced by BVTSDK::Head::GetHeadName().
RetVal BVTHead_SetRange (BVTHead obj, float start, float stop)
Set the range to be acquired.
Parameters:
obj Object pointer
start Start range in meters
stop Stop range in meters
Referenced by BVTSDK::Head::SetRange().
float BVTHead_GetStartRange (BVTHead obj)
Retrieve the current starting range in meters.
Parameters:
obj Object pointer
Referenced by BVTSDK::Head::GetStartRange().
float BVTHead_GetStopRange (BVTHead obj)
Retrieve the current stopping range in meters.
Parameters:
obj Object pointer
Referenced by BVTSDK::Head::GetStopRange().
float BVTHead_GetMinimumRange (BVTHead obj)
Return the minimum allowable range for this sonar.
Parameters:
obj Object pointer
Referenced by BVTSDK::Head::GetMinimumRange().
float BVTHead_GetMaximumRange (BVTHead obj)
Return the maximum allowable range for this sonar.
Parameters:
obj Object pointer
Referenced by BVTSDK::Head::GetMaximumRange().
int BVTHead_GetFluidType (BVTHead obj)
Return the type of water the head is in.
The returned value will correspond to one of the FLUID_* constants.
Parameters:
obj Object pointer
Referenced by BVTSDK::Head::GetFluidType().
RetVal BVTHead_SetFluidType (BVTHead obj, int fluid)
Set the type of water the head is in.
Parameters:
obj Object pointer
fluid The fluid type (one of the FLUID_* constants)
Referenced by BVTSDK::Head::SetFluidType().
int BVTHead_GetSoundSpeed (BVTHead obj)
Return the speed of sound in water.
Parameters:
obj Object pointer
Referenced by BVTSDK::Head::GetSoundSpeed().
RetVal BVTHead_SetSoundSpeed (BVTHead obj, int speed)
Set the speed of sound in water.
Parameters:
obj Object pointer
speed Sound speed in water
Referenced by BVTSDK::Head::SetSoundSpeed().
float BVTHead_GetGainAdjustment (BVTHead obj)
Return the additional analog gain in dB.
Parameters:
obj Object pointer
Referenced by BVTSDK::Head::GetGainAdjustment().
RetVal BVTHead_SetGainAdjustment (BVTHead obj, float gain)
Set the additional analog gain.
Note: Some systems don't support gain adjustment.
Parameters:
obj Object pointer
gain Additional analog gain in dB
Referenced by BVTSDK::Head::SetGainAdjustment().
float BVTHead_GetTVGSlope (BVTHead obj)
Return the time variable gain in dB/meter.
Parameters:
obj Object pointer
Referenced by BVTSDK::Head::GetTVGSlope().
RetVal BVTHead_SetTVGSlope (BVTHead obj, float tvg)
Set the time variable analog gain.
Note: Some systems don't support TVG
Parameters:
obj Object pointer
tvg Time variable gain in dB/meter
Referenced by BVTSDK::Head::SetTVGSlope().
int BVTHead_GetCenterFreq (BVTHead obj)
Return the center frequency(in Hz) of this head.
Parameters:
obj Object pointer
Referenced by BVTSDK::Head::GetCenterFreq().
int BVTHead_GetPingCount (BVTHead obj)
Return the number of pings 'in' this head A head attached to a file might have more than one ping recorded.
However, a networked sonar will only have a single ping.
Parameters:
obj Object pointer
Referenced by BVTSDK::Head::GetPingCount().
RetVal BVTHead_GetPing (BVTHead obj, int ping_num, BVTPing * ping)
Retrieve a Ping from the Head If ping_num is less than 0, return the next ping in the file.
Otherwise, load the specified ping. If the Head is attached to a 'live' sonar (network), then GetPing always acquires a new ping.
Parameters:
obj Object pointer
ping_num The ping number to return
ping The returned Ping object
Referenced by BVTSDK::Head::GetPing().
RetVal BVTHead_PutPing (BVTHead obj, const BVTPing ping)
Write a ping to a file.
Parameters:
obj Object pointer
ping The ping to write out
Referenced by BVTSDK::Head::PutPing().
RetVal BVTHead_SetImageRes (BVTHead obj, int res)
Set the image processing resolution.
The RES_AUTO setting is highly recommended, as it adapts via a formula according to the stop range, whereas the other ranges are fixed values, and should only be used in specialized cases, such as requesting high resolution for longer distances (which will increase the processing time required to create the image). R-Theta images may use either this funtion or SetRangeResolution(), depending on the degree of control required.
Parameters:
obj Object pointer
res Resolution constant (RES_*)
Referenced by BVTSDK::Head::SetImageRes().
RetVal BVTHead_SetRangeResolution (BVTHead obj, float resolution_in_meters)
Requests a range resolution for R-Theta images.
Also affects the range resolution for RangeData. Note that the exact range resolution may not be available, and the closest resolution will be set. The actual resolution can be obtained by querying the returned image or RangeData object.
Parameters:
obj Object pointer
resolution_in_meters Range resolution, in meters
Referenced by BVTSDK::Head::SetRangeResolution().
RetVal BVTHead_SetImageReqSize (BVTHead obj, int height, int width)
Set the requested out image size The processing code will attempt to process images at the specified size.
However, it doesn't guarantee that the final output will match this size. NOTE: For R-Theta images, only the width is used, and the image will be created with that exact width. Height will depend on the range, and the resolution set. (See SetImageRes() and SetRangeResolution())
Parameters:
obj Object pointer
height The requested height
width The requested width
Referenced by BVTSDK::Head::SetImageReqSize().
RetVal BVTHead_SetRemoteBeamForming (BVTHead obj, int enable)
NOTE: this option is only valid for some sonars, in specific circumstances, and should only be used on advice from the factory.
By default, beamforming is done on the local system. If you call this function with enable=true, the SDK will request that the remote sonar handle the majority of the beamforming. This operation applies the next time GetPing is called.
Parameters:
obj Object pointer
enable Enable/Disable remote beamformer. (using 1 or 0 to enable or disable)
Referenced by BVTSDK::Head::SetRemoteBeamForming().
RetVal BVTHead_SetRawDataSending (BVTHead obj, int enable)
NOTE: this option is only valid for some sonars, in specific circumstances, and should only be used on advice from the factory.
By default, the sonar sends data suitable for saving to a .son file. If you are not saving files, AND are recieving processed data thru setting one of the other options, you can call this function with enable=false to reduce the amount of network bandwidth needed. . This operation applies the next time GetPing is called.
Parameters:
obj Object pointer
enable Enable/Disable raw ping data. (using 1 or 0 to enable or disable)
Referenced by BVTSDK::Head::SetRawDataSending().
RetVal BVTHead_SetRemoteImageForming (BVTHead obj, int enable)
NOTE: this option is only valid for some sonars, in specific circumstances, and should only be used on advice from the factory.
By default, image forming is done on the local system. If you call this function with en=true, the SDK will request that the remote sonar handle the image forming. This option is slightly different than remote beam-forming, with all processing done on the sonar, and only the complete image sent over the network connection. This operation applies the next time GetPing is called.
Parameters:
obj Object pointer
enable Enable/Disable remote image forming. (using 1 or 0 to enable or disable)
Referenced by BVTSDK::Head::SetRemoteImageForming().
RetVal BVTHead_SetImageType (BVTHead obj, int type)
Set the type of image output.
NOTE: See SetImageReqSize() for important issues regarding image size.
Parameters:
obj Object pointer
type Image type constant (IMAGE_*)
Referenced by BVTSDK::Head::SetImageType().
int BVTHead_GetImageFilterFlags (BVTHead obj)
Return the filter flags.
Parameters:
obj Object pointer
Referenced by BVTSDK::Head::GetImageFilterFlags().
RetVal BVTHead_SetImageFilterFlags (BVTHead obj, int flags)
Set the filter flags.
Parameters:
obj Object pointer
flags Image filter flags (bit field)
Referenced by BVTSDK::Head::SetImageFilterFlags().
RetVal BVTHead_SetRangeDataThreshold (BVTHead obj, unsigned short noise_threshold)
** EXPERIMENTAL ** Sets the intensity value below which data is considered to be noise.
Values above this threshold are included in the algorithm which attempts to determine the target edge. This is NOT a simple threshold above which the first value encountered is considered the target edge. This is the same intensity value returned in a MagImage, with a range of an unsigned 16-bit integer. If not set, the default is currently set to 1000.
NOTE: This only applies to specialized BlueView sonars.
Parameters:
obj Object pointer
noise_threshold Threshold below which is considered noise
Referenced by BVTSDK::Head::SetRangeDataThreshold().
RetVal BVTHead_SetTxEnable (BVTHead obj, int enableTx)
By default, the sonar transmits pings.
This function allows the user to disable transmit. This can be useful to get background noise measurements. Note that this is not implemented on all sonars.
Parameters:
obj Object pointer
enableTx If 0, disable the sonar transmission of pings.
Referenced by BVTSDK::Head::SetTxEnable().
RetVal BVTHead_GetMountingOrientation (BVTHead obj, double * X_axis_degrees, double * Y_axis_degrees, double * Z_axis_degrees)
** Preliminary support - may change in later SDK versions **
Position of the sonar positioner relative to the boat.
Parameters:
obj Object pointer
X_axis_degrees rotation about X axis
Y_axis_degrees rotation about Y axis
Z_axis_degrees rotation about Z axis
Referenced by BVTSDK::Head::GetMountingOrientation().
RetVal BVTHead_SetMountingOrientation (BVTHead obj, double X_axis_degrees, double Y_axis_degrees, double Z_axis_degrees)
** Preliminary support - may change in later SDK versions **
Position of the sonar positioner relative to the boat.
Parameters:
obj Object pointer
X_axis_degrees rotation about X axis
Y_axis_degrees rotation about Y axis
Z_axis_degrees rotation about Z axis
Referenced by BVTSDK::Head::SetMountingOrientation().